-- Batch D: Orbita, Orvibo, PHGLock, Philips, Qrio (+2 each)

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='orbita-hotel-rfid'), (SELECT id FROM brands WHERE slug='orbita'), 'Orbita S3072 RFID Cylinder Lock', 'orbita-s3072-cylinder', 'S3072', 'RFID cylinder lock for cabinets/lockers. Mifare 13.56MHz. Standalone. 2x CR2450, 30000 openings. Zinc alloy. For gym, office, spa. Anti-rust.', 5000, 'rfid', NULL, 0, 'CR2450', 2, 24, 400, '0', 'AES-128', 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, '0', 0.01, 10.0, 50, 0, 0, 2000, 0, '13.56MHz', 3, 'internal', '[]', 3.8, 200, 'Orbita S3072 Cabinet Lock Review 2026', 'Orbita S3072 RFID cabinet/locker lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='orbita-hotel-rfid'), (SELECT id FROM brands WHERE slug='orbita'), 'Orbita E4131 WiFi Online Hotel Lock', 'orbita-e4131-wifi', 'E4131', 'WiFi online hotel mortise lock. Real-time monitoring. RFID + PIN + BLE + mechanical override. PMS integration. 304 stainless. 4x AA, 12 months. CE/FCC.', 28000, 'wifi', 'rfid', 0, 'AA', 4, 12, 2500, '0', 'AES-128', 0, 1, 1, 0, 0, 1, 1, 1, 1, 32, 70, 0, '0', 0.15, 300.0, 100, 20, 0, 5000, 50, '2.4GHz', 20, 'internal', '["Orbita Hotel Cloud","PMS Integration"]', 4.1, 250, 'Orbita E4131 WiFi Hotel Lock Review 2026', 'Orbita E4131 WiFi online hotel lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='orvibo-smart-lock'), (SELECT id FROM brands WHERE slug='orvibo'), 'Orvibo C1 Smart Fingerprint Lock', 'orvibo-c1-fingerprint', 'C1-FP', 'Budget fingerprint lock. Fingerprint + PIN + IC card + key. BLE app (HomeMate). Auto-lock. Anti-pry. 4x AA. Zinc alloy. Door 40-65mm.', 15000, 'bluetooth', NULL, 0, 'AA', 4, 12, 2200, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 40, 65, 0, '0', 0.06, 120.0, 10, 20, 50, 20, 30, '2.4GHz', 10, 'internal', '["HomeMate App"]', 3.9, 500, 'Orvibo C1 Review 2026', 'Orvibo C1 budget fingerprint smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='orvibo-smart-lock'), (SELECT id FROM brands WHERE slug='orvibo'), 'Orvibo T1 WiFi Video Smart Lock', 'orvibo-t1-video', 'T1-VID', 'WiFi smart lock with camera. 1080p video doorbell built-in. Fingerprint + PIN + IC card + face detect + app + key. Push-pull handle. 5000mAh Li-ion.', 45000, 'wifi', 'bluetooth', 0, 'lithium-ion', 1, 6, 4000, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 120, 0, '0', 0.20, 500.0, 10, 30, 50, 30, 100, '2.4GHz', 20, 'internal', '["HomeMate App","Amazon Alexa"]', 4.0, 300, 'Orvibo T1 Video Lock Review 2026', 'Orvibo T1 video doorbell + smart lock combo.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='phglock-fp'), (SELECT id FROM brands WHERE slug='phglock'), 'PHGLock FP8190 Face Recognition Lock', 'phglock-fp8190', 'FP8190', 'Face recognition + fingerprint + PIN + RFID card + key. WiFi remote. Push-pull handle. 4x AA, 12 months. Anti-pry alarm. Popular in Vietnam market.', 25000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 3000, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 40, 65, 0, '0', 0.12, 250.0, 10, 20, 100, 50, 50, '2.4GHz', 20, 'internal', '["PHGLock App"]', 4.0, 600, 'PHGLock FP8190 Face Lock Review 2026', 'PHGLock FP8190 face recognition lock Vietnam.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='phglock-fp'), (SELECT id FROM brands WHERE slug='phglock'), 'PHGLock FP5293 Glass Door Lock', 'phglock-fp5293-glass', 'FP5293', 'Glass door fingerprint lock. Fingerprint + PIN + RFID + key. For frameless glass doors 10-12mm. BLE app. Auto-lock. Stainless steel bracket.', 18000, 'bluetooth', NULL, 0, 'AA', 4, 12, 2500, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, '0', 0.06, 120.0, 10, 20, 50, 30, 30, '2.4GHz', 10, 'internal', '["PHGLock App"]', 3.8, 400, 'PHGLock FP5293 Glass Door Review 2026', 'PHGLock FP5293 glass door fingerprint lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='philips' LIMIT 1), (SELECT id FROM brands WHERE slug='philips'), 'Philips EasyKey 9300 3D Face Lock', 'philips-easykey-9300', 'DDL9300', '3D face + fingerprint + PIN + IC card + key. WiFi remote. Push-pull. Anti-pry alarm. 8x AA, 12 months. Door 40-100mm. Cat-eye proof.', 50000, 'wifi', 'bluetooth', 0, 'AA', 8, 12, 3800, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 100, 0, '0', 0.15, 400.0, 10, 30, 100, 50, 100, '2.4GHz', 20, 'internal', '["Philips EasyKey App","Amazon Alexa"]', 4.3, 800, 'Philips EasyKey 9300 Face Lock Review 2026', 'Philips EasyKey 9300. 3D face recognition premium lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='philips' LIMIT 1), (SELECT id FROM brands WHERE slug='philips'), 'Philips EasyKey 5100 Budget Deadbolt', 'philips-easykey-5100', 'DDL5100', 'Budget fingerprint deadbolt. Fingerprint + PIN + IC card + key. BLE app. Auto-lock. 4x AA, 12 months. Compact design.', 15000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1500, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 55, 0, '0', 0.06, 100.0, 10, 30, 50, 30, 30, '2.4GHz', 10, 'internal', '["Philips EasyKey App"]', 4.0, 1500, 'Philips EasyKey 5100 Review 2026', 'Philips EasyKey 5100 budget fingerprint deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='qrio' LIMIT 1), (SELECT id FROM brands WHERE slug='qrio'), 'Qrio Lock Q-SL2T (Latest)', 'qrio-lock-q-sl2t', 'Q-SL2T', 'Latest Qrio Lock. BLE 5.0. Smaller, faster. Auto-lock/unlock. Hub sold separately for remote. Alexa + Google (via Hub). Apple Watch. 2x CR123A, 12+ months. 3M adhesive. SesameOS alternative. Japan market.', 16000, 'bluetooth', NULL, 0, 'CR123A', 2, 12, 210, '0', 'AES-256', 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, '0', 0.02, 50.0, 10, 0, 0, 0, 100, '2.4GHz', 10, 'internal', '["Amazon Alexa (via Hub)","Google Assistant (via Hub)","Apple Watch"]', 4.1, 3000, 'Qrio Lock Q-SL2T Review 2026', 'Qrio Q-SL2T latest Japanese smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='qrio' LIMIT 1), (SELECT id FROM brands WHERE slug='qrio'), 'Qrio Pad Q-KP2T NFC Keypad', 'qrio-pad-q-kp2t', 'Q-KP2T', 'NFC card + PIN keypad for Qrio Lock. Weather-resistant outdoor mount. NFC tags included. 6-digit PIN codes. BLE pairing. 3V CR123A x2. Kids/guests without smartphone.', 7000, 'bluetooth', 'nfc', 0, 'CR123A', 2, 12, 160, '0', 'AES-256', 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, '0', 0.01, 15.0, 10, 20, 0, 20, 0, '13.56MHz', 3, 'internal', '["Qrio Lock"]', 4.0, 1500, 'Qrio Pad Q-KP2T Review 2026', 'Qrio Pad Q-KP2T NFC keypad accessory.');

-- Tags Batch D
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'rfid' FROM products WHERE slug IN ('orbita-s3072-cylinder');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'wifi' FROM products WHERE slug IN ('orbita-e4131-wifi','orvibo-t1-video','phglock-fp8190','philips-easykey-9300');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'bluetooth' FROM products WHERE slug IN ('orvibo-c1-fingerprint','phglock-fp5293-glass','philips-easykey-5100','qrio-lock-q-sl2t','qrio-pad-q-kp2t');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'fingerprint' FROM products WHERE slug IN ('orvibo-c1-fingerprint','orvibo-t1-video','phglock-fp8190','phglock-fp5293-glass','philips-easykey-9300','philips-easykey-5100');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'face-recognition' FROM products WHERE slug IN ('phglock-fp8190','philips-easykey-9300');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'camera' FROM products WHERE slug='orvibo-t1-video';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'budget' FROM products WHERE slug IN ('orbita-s3072-cylinder','orvibo-c1-fingerprint','qrio-pad-q-kp2t','philips-easykey-5100');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'premium' FROM products WHERE slug IN ('philips-easykey-9300','orvibo-t1-video');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'mid' FROM products WHERE slug IN ('orbita-e4131-wifi','phglock-fp8190','phglock-fp5293-glass','qrio-lock-q-sl2t');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'hotel' FROM products WHERE slug IN ('orbita-s3072-cylinder','orbita-e4131-wifi');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'apartment' FROM products WHERE slug IN ('qrio-lock-q-sl2t','phglock-fp8190');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'family' FROM products WHERE slug IN ('philips-easykey-9300','orvibo-t1-video');
