-- Batch B: Danalock, Defiant, EPIC, Godrej, HARFO (+2 each)

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='danalock' LIMIT 1), (SELECT id FROM brands WHERE slug='danalock'), 'Danalock V3 Z-Wave Plus Universal', 'danalock-v3-ztze', 'V3-ZTZE', 'Z-Wave Plus + BLE retrofit cylinder lock. SmartThings, Hubitat, Ring Alarm compatible. 256-bit AES. 4x CR123A, 12 months (9000 openings). 195g. Auto-lock, geo-unlock. CE/FCC.', 22000, 'z-wave', 'bluetooth', 0, 'CR123A', 4, 12, 195, '0', 'AES-256', 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, '0', 0.03, 80.0, 10, 0, 0, 0, 100, '908.42MHz', 15, 'internal', '["Z-Wave Plus","SmartThings","Ring Alarm","Danalock App"]', 4.0, 600, 'Danalock V3 Z-Wave Review 2026', 'Danalock V3 Z-Wave Plus. SmartThings compatible European retrofit lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='danalock' LIMIT 1), (SELECT id FROM brands WHERE slug='danalock'), 'Danalock Danapad V3 Keypad', 'danalock-danapad-v3', 'DANAPAD-V3', 'Wireless BLE keypad for Danalock V3. 20 PIN codes. Night-mode backlight. Outdoor mount, weather-resistant. 4x AAA, 12 months. Pairs with any Danalock V3 variant.', 8000, 'bluetooth', NULL, 0, 'AAA', 4, 12, 150, '0', 'AES-256', 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, '0', 0.01, 15.0, 10, 20, 0, 0, 0, '2.4GHz', 5, 'internal', '["Danalock V3"]', 3.8, 400, 'Danalock Danapad V3 Review 2026', 'Danapad V3 wireless keypad for Danalock V3.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='defiant-hubspace-wifi'), (SELECT id FROM brands WHERE slug='defiant'), 'Defiant Compact WiFi Deadbolt (Hubspace)', 'defiant-compact-wifi-deadbolt', 'HSGC9X2D02', 'Compact WiFi deadbolt. Hubspace app. 20 user codes. Auto-lock, Alexa+Google voice. ANSI Grade 3. 4x AA, 12 months. Satin nickel.', 8000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1100, '3', 'AES-128', 0, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 20, 0, 0, 50, '2.4GHz', 20, 'internal', '["Hubspace","Amazon Alexa","Google Assistant"]', 3.7, 1500, 'Defiant Compact WiFi Deadbolt Review 2026', 'Defiant Compact WiFi deadbolt. Budget smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='defiant-hubspace-wifi'), (SELECT id FROM brands WHERE slug='defiant'), 'Defiant Biometric WiFi Deadbolt', 'defiant-biometric-wifi', 'HSGC-BIO', 'Fingerprint + keypad + WiFi. Hubspace. 50 fingerprints, 20 codes. Alexa+Google. ANSI Grade 3. 4x AA. Anti-saw rod.', 13000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1300, '3', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 20, 50, 0, 50, '2.4GHz', 20, 'internal', '["Hubspace","Amazon Alexa","Google Assistant"]', 3.9, 800, 'Defiant Biometric WiFi Review 2026', 'Defiant Biometric WiFi. Fingerprint + WiFi budget lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='epic-generation'), (SELECT id FROM brands WHERE slug='epic'), 'EPIC 5G Pro-2 Push-Pull Lock', 'epic-5g-pro2', 'ES-5G-PRO2', 'Push-pull digital lock. Fingerprint (100) + PIN + RFID (200) + BLE app + key. Auto-lock, fire alarm. Korean market leader. 4x AA, 12 months.', 30000, 'bluetooth', NULL, 0, 'AA', 4, 12, 2800, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 40, 80, 0, '0', 0.06, 150.0, 20, 50, 100, 200, 100, '2.4GHz', 10, 'internal', '["EPIC Things App"]', 4.1, 900, 'EPIC 5G Pro-2 Review 2026', 'EPIC 5G Pro-2. Korean push-pull digital lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='epic-generation'), (SELECT id FROM brands WHERE slug='epic'), 'EPIC ES-F300D Rim Lock', 'epic-es-f300d', 'ES-F300D', 'Rim-type digital lock for Korean apartment doors. Fingerprint + PIN + RFID card + key. Double-lock. Anti-prank alarm, fire detection. 4x AA.', 20000, 'none', NULL, 0, 'AA', 4, 12, 2000, '0', 'AES-128', 1, 1, 1, 0, 0, 0, 1, 1, 1, 40, 60, 0, '0', 0.04, 100.0, 20, 30, 80, 100, 0, 'none', 0, 'none', '[]', 4.0, 700, 'EPIC ES-F300D Review 2026', 'EPIC ES-F300D. Korean rim digital lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='godrej-advantis'), (SELECT id FROM brands WHERE slug='godrej'), 'Godrej Catus Connect WiFi Smart Lock', 'godrej-catus-connect', 'CATUS-CON', 'WiFi push-pull handle lock. Fingerprint + PIN + RFID + app + mechanical key. WiFi built-in. Alexa+Google. Auto-lock, anti-pry alarm. 4x AA, 12 months. Door 40-70mm.', 22000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 2800, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 70, 0, '0', 0.10, 200.0, 10, 30, 80, 50, 50, '2.4GHz', 20, 'internal', '["Godrej App","Amazon Alexa","Google Assistant"]', 4.0, 1500, 'Godrej Catus Connect Review 2026', 'Godrej Catus Connect. WiFi push-pull smart lock India.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='godrej-advantis'), (SELECT id FROM brands WHERE slug='godrej'), 'Godrej Advantis Crystal Smart Lock', 'godrej-advantis-crystal', 'ADV-CRYSTAL', 'Budget fingerprint + PIN + RFID + key deadbolt. BLE app. Anti-tamper alarm. 4x AA, 12 months. Door 35-55mm. Made in India.', 12000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1800, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 55, 0, '0', 0.06, 100.0, 10, 20, 50, 30, 20, '2.4GHz', 10, 'internal', '["Godrej App"]', 3.9, 800, 'Godrej Advantis Crystal Review 2026', 'Godrej Advantis Crystal. Budget Indian smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='harfo-fingerprint-handle'), (SELECT id FROM brands WHERE slug='harfo'), 'HARFO HFL01 Deadbolt Smart Lock', 'harfo-hfl01-deadbolt', 'HFL01', 'Deadbolt-type. Fingerprint + passcode + IC card + BLE app + mechanical key. 250 codes. Anti-peep. Auto-lock. Reversible. 4x AA, 12 months. ANSI Grade 3.', 10000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1800, '3', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 56, 54, '60,70', 0.06, 120.0, 10, 250, 99, 50, 50, '2.4GHz', 10, 'internal', '["HARFO App"]', 4.0, 2000, 'HARFO HFL01 Review 2026', 'HARFO HFL01. Budget fingerprint deadbolt smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT id FROM product_series WHERE slug='harfo-fingerprint-handle'), (SELECT id FROM brands WHERE slug='harfo'), 'HARFO HF-FG Fingerprint Lever Lock', 'harfo-hf-fg-lever', 'HF-FG', 'Lever handle. Fingerprint + passcode + IC card + key. Reversible for left/right doors. Auto-lock. 4x AA. Budget lever smart lock.', 8000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1600, '0', 'AES-128', 1, 1, 1, 0, 0, 0, 1, 1, 1, 35, 56, 54, '60,70', 0.06, 100.0, 10, 100, 50, 30, 20, '2.4GHz', 10, 'internal', '[]', 3.8, 1000, 'HARFO HF-FG Lever Review 2026', 'HARFO HF-FG. Budget fingerprint lever lock.');

-- Tags for Batch B
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'z-wave' FROM products WHERE slug='danalock-v3-ztze';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'wifi' FROM products WHERE slug IN ('defiant-compact-wifi-deadbolt','defiant-biometric-wifi','godrej-catus-connect');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'bluetooth' FROM products WHERE slug IN ('danalock-danapad-v3','epic-5g-pro2','godrej-advantis-crystal','harfo-hfl01-deadbolt','harfo-hf-fg-lever');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'fingerprint' FROM products WHERE slug IN ('defiant-biometric-wifi','epic-5g-pro2','epic-es-f300d','godrej-catus-connect','godrej-advantis-crystal','harfo-hfl01-deadbolt','harfo-hf-fg-lever');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'keypad' FROM products WHERE slug IN ('danalock-danapad-v3','defiant-compact-wifi-deadbolt','defiant-biometric-wifi','epic-5g-pro2','epic-es-f300d','godrej-catus-connect','godrej-advantis-crystal','harfo-hfl01-deadbolt');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'retrofit' FROM products WHERE slug IN ('danalock-v3-ztze');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'budget' FROM products WHERE slug IN ('danalock-danapad-v3','defiant-compact-wifi-deadbolt','harfo-hfl01-deadbolt','harfo-hf-fg-lever','godrej-advantis-crystal');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'mid' FROM products WHERE slug IN ('danalock-v3-ztze','defiant-biometric-wifi','epic-es-f300d','godrej-catus-connect','epic-5g-pro2');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'apartment' FROM products WHERE slug IN ('danalock-v3-ztze','epic-es-f300d','defiant-compact-wifi-deadbolt');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'family' FROM products WHERE slug IN ('godrej-catus-connect','harfo-hfl01-deadbolt','epic-5g-pro2');
