-- Batch F: Solity, SwitchBot, TCL, Tedee, Teeho (+2 each)
-- Batch G: Veise, Weiser, Wyze, Xiaomi (+2 each)
-- Batch H: Dessmann, Eufy, Level, Samsung, Ultraloq, ZKTeco (+1 each)

-- SOLITY
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='solity' LIMIT 1), (SELECT id FROM brands WHERE slug='solity'), 'Solity GM-6000BKF Push-Pull Lock', 'solity-gm6000bkf', 'GM-6000BKF', 'Push-pull handle. Fingerprint + PIN + RFID + key. Korean mortise. Auto-lock. Fire detection. Anti-pry alarm. 4x AA, 12 months.', 25000, 'none', NULL, 0, 'AA', 4, 12, 3000, '0', 'AES-128', 1, 1, 1, 0, 0, 0, 1, 1, 1, 40, 80, 0, '0', 0.06, 150.0, 20, 30, 100, 100, 0, 'none', 0, 'none', '[]', 4.1, 600, 'Solity GM-6000BKF Review 2026', 'Solity GM-6000BKF Korean push-pull lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='solity' LIMIT 1), (SELECT id FROM brands WHERE slug='solity'), 'Solity WM-65 WiFi Smart Rim Lock', 'solity-wm65-wifi', 'WM-65', 'WiFi rim lock. PIN + RFID card + BLE app + key. WiFi remote (Solity Lite app). Auto-lock. Emergency battery. Korean apartment standard. 4x AA.', 18000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 2200, '0', 'AES-128', 0, 1, 1, 0, 0, 1, 1, 1, 1, 40, 60, 0, '0', 0.10, 200.0, 20, 30, 0, 100, 50, '2.4GHz', 20, 'internal', '["Solity Lite App"]', 4.0, 400, 'Solity WM-65 WiFi Review 2026', 'Solity WM-65 WiFi Korean rim lock.');

-- SWITCHBOT
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='switchbot' LIMIT 1), (SELECT id FROM brands WHERE slug='switchbot'), 'SwitchBot Lock Pro (Matter Compatible)', 'switchbot-lock-pro', 'W3500010', 'Dual-latch support (single+double). Matter (via Hub). BLE + WiFi (via Hub). Quick key with NFC tags. Auto-lock/unlock. Keypad (sold separately). 2x CR123A, 9 months. 3M adhesive. Largest compatibility range.', 13000, 'bluetooth', NULL, 1, 'CR123A', 2, 9, 350, '0', 'AES-128', 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, '0', 0.03, 60.0, 10, 0, 0, 0, 100, '2.4GHz', 10, 'internal', '["Amazon Alexa","Google Assistant","Apple HomeKit (via Hub)","Matter (via Hub)","SwitchBot App","IFTTT"]', 4.2, 5000, 'SwitchBot Lock Pro Review 2026', 'SwitchBot Lock Pro. Matter, dual-latch, NFC.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='switchbot' LIMIT 1), (SELECT id FROM brands WHERE slug='switchbot'), 'SwitchBot Keypad Touch (Fingerprint)', 'switchbot-keypad-touch', 'W2500020', 'Fingerprint + PIN keypad companion for SwitchBot Lock. 100 fingerprints (0.3s). 100 passcodes. NFC card (included). IP65 waterproof. 2x CR123A, 2 years.', 6000, 'bluetooth', 'nfc', 0, 'CR123A', 2, 24, 130, '0', 'AES-128', 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, '0', 0.01, 15.0, 10, 100, 100, 10, 0, '13.56MHz', 3, 'internal', '["SwitchBot Lock"]', 4.3, 4000, 'SwitchBot Keypad Touch Review 2026', 'SwitchBot Keypad Touch fingerprint accessory.');

-- TCL
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='tcl' LIMIT 1), (SELECT id FROM brands WHERE slug='tcl'), 'TCL K6P 3D Face Recognition WiFi Lock', 'tcl-k6p-face', 'K6P', '3D face + fingerprint + PIN + IC card + app + key. WiFi built-in. Push-pull handle. Cat-eye proof. 5000mAh Li-ion, 6 months. Anti-pry, fire detection.', 35000, 'wifi', 'bluetooth', 0, 'lithium-ion', 1, 6, 3500, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 120, 0, '0', 0.15, 350.0, 10, 30, 100, 50, 100, '2.4GHz', 20, 'internal', '["TCL Smart Home","Amazon Alexa"]', 4.0, 500, 'TCL K6P Face Lock Review 2026', 'TCL K6P 3D face WiFi push-pull lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='tcl' LIMIT 1), (SELECT id FROM brands WHERE slug='tcl'), 'TCL K2A Budget Fingerprint Lock', 'tcl-k2a-budget', 'K2A', 'Budget fingerprint + PIN + IC card + key. BLE app. Auto-lock. Anti-pry alarm. 4x AA, 12 months. Door 40-65mm. Entry-level TCL lock.', 12000, 'bluetooth', NULL, 0, 'AA', 4, 12, 2000, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 40, 65, 0, '0', 0.06, 120.0, 10, 20, 50, 30, 30, '2.4GHz', 10, 'internal', '["TCL Smart Home"]', 3.8, 800, 'TCL K2A Budget Lock Review 2026', 'TCL K2A budget fingerprint smart lock.');

-- TEDEE
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='tedee' LIMIT 1), (SELECT id FROM brands WHERE slug='tedee'), 'Tedee PRO Aluminium Smart Lock', 'tedee-pro-aluminium', 'PRO-AL', 'Premium aluminium retrofit. BLE 5.0. Rechargeable Li-Po, 7 months. Ø56x57mm. TLS 1.3 (AV-Test). Tedee Bridge for remote/HomeKit/Alexa/Google/Matter. Auto-lock, auto-unlock. Web portal key sharing.', 25000, 'bluetooth', NULL, 1, 'lithium-ion', 1, 7, 190, '0', 'TLS-1.3', 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, '0', 0.02, 50.0, 10, 0, 0, 0, 100, '2.4GHz', 10, 'internal', '["Apple HomeKit (via Bridge)","Amazon Alexa","Google Home","Matter (via Bridge)","Home Assistant"]', 4.4, 3000, 'Tedee PRO Review 2026', 'Tedee PRO aluminium. Premium European retrofit lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='tedee' LIMIT 1), (SELECT id FROM brands WHERE slug='tedee'), 'Tedee Keypad (Companion)', 'tedee-keypad', 'KPD-1', 'Wireless BLE keypad for Tedee locks. PIN codes. Outdoor weatherproof. 3x AAA, 12 months. Pair with any Tedee lock. Guest codes. Night mode backlight.', 8000, 'bluetooth', NULL, 0, 'AAA', 3, 12, 140, '0', 'TLS-1.3', 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, '0', 0.01, 15.0, 10, 30, 0, 0, 0, '2.4GHz', 5, 'internal', '["Tedee Lock"]', 4.0, 1500, 'Tedee Keypad Review 2026', 'Tedee Keypad wireless companion accessory.');

-- TEEHO
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='teeho' LIMIT 1), (SELECT id FROM brands WHERE slug='teeho'), 'Teeho TE002W WiFi Smart Deadbolt', 'teeho-te002w-wifi', 'TE002W', 'WiFi built-in (no gateway). Fingerprint (50) + PIN (250) + IC card + app + key. Auto-lock. Anti-peep. Alexa + Google. IP54. ANSI Grade 3. 4x AA, 12 months.', 8000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1500, '3', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 250, 50, 50, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","Teeho App"]', 4.0, 3000, 'Teeho TE002W WiFi Review 2026', 'Teeho TE002W WiFi fingerprint deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='teeho' LIMIT 1), (SELECT id FROM brands WHERE slug='teeho'), 'Teeho TE001 Keypad Deadbolt (No Fingerprint)', 'teeho-te001-keypad', 'TE001', 'Budget keypad deadbolt. PIN (250) + BLE app + key. No fingerprint. Auto-lock. Anti-peep. ANSI Grade 3. 4x AA, 12 months. Ultra-budget entry.', 4000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1200, '3', 'AES-128', 0, 1, 1, 0, 0, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.05, 80.0, 10, 250, 0, 0, 20, '2.4GHz', 10, 'internal', '["Teeho App"]', 3.8, 4000, 'Teeho TE001 Keypad Review 2026', 'Teeho TE001 ultra-budget keypad deadbolt.');

-- VEISE
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='veise' LIMIT 1), (SELECT id FROM brands WHERE slug='veise'), 'Veise VE027 WiFi Built-in Deadbolt', 'veise-ve027-wifi', 'VE027', 'Built-in WiFi (no gateway). Fingerprint + PIN + RFID + app + key. Alexa + Google. Auto-lock. IP55. Anti-peep. USB-C emergency. 4x AA. ANSI Grade 3.', 9000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1500, '3', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 100, 20, 20, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","KK Home App"]', 4.0, 2500, 'Veise VE027 WiFi Review 2026', 'Veise VE027 WiFi built-in smart deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='veise' LIMIT 1), (SELECT id FROM brands WHERE slug='veise'), 'Veise KS02A Knob Smart Lock', 'veise-ks02a-knob', 'KS02A', 'Smart knob (no lever). Fingerprint + PIN + BLE app + key. Compact design. Auto-lock. Anti-peep. 4x AA, 10 months. Budget knob lock. ANSI Grade 3.', 5000, 'bluetooth', NULL, 0, 'AA', 4, 10, 1100, '3', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.06, 100.0, 10, 50, 20, 0, 20, '2.4GHz', 10, 'internal', '["DD Lock App"]', 3.7, 1500, 'Veise KS02A Knob Review 2026', 'Veise KS02A budget smart knob lock.');

-- WEISER
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='weiser' LIMIT 1), (SELECT id FROM brands WHERE slug='weiser'), 'Weiser Halo WiFi Fingerprint Deadbolt', 'weiser-halo-wifi-fingerprint', '?"9GED25000', 'WiFi + fingerprint deadbolt. Fingerprint + passcode + key. Built-in WiFi. Alexa + Google. Auto-lock. 2x CR2 + 4x AA, 12 months. ANSI Grade 2. SmartKey re-key. Canadian market.', 25000, 'wifi', NULL, 0, 'AA', 4, 12, 1600, '2', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 30, 50, 0, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","Weiser App"]', 4.1, 1500, 'Weiser Halo WiFi Fingerprint Review 2026', 'Weiser Halo WiFi fingerprint. Canadian premium deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='weiser' LIMIT 1), (SELECT id FROM brands WHERE slug='weiser'), 'Weiser Premis HomeKit Deadbolt', 'weiser-premis-homekit', '?"9GED22000', 'Apple HomeKit native deadbolt. BLE. Siri voice. Auto-lock. SecureScreen anti-smudge. SmartKey re-key. ANSI Grade 2. 4x AA. Canadian HomeKit-first lock.', 22000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1400, '2', 'AES-128', 0, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.06, 120.0, 10, 30, 0, 0, 50, '2.4GHz', 10, 'internal', '["Apple HomeKit","Siri"]', 4.0, 800, 'Weiser Premis HomeKit Review 2026', 'Weiser Premis Apple HomeKit smart lock Canada.');

-- WYZE
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='wyze' LIMIT 1), (SELECT id FROM brands WHERE slug='wyze'), 'Wyze Lock Bolt Original (BLE Only)', 'wyze-lock-bolt-ble', 'LOCK-BOLT-OG', 'BLE-only fingerprint deadbolt. Fingerprint (50) + keypad + key. No WiFi (no remote). Ultra-budget. 0.3s fingerprint. BHMA Grade 2. 4x AA, 6 months. AES-128.', 5000, 'bluetooth', NULL, 0, 'AA', 4, 6, 1100, '2', 'AES-128', 1, 1, 1, 0, 0, 0, 1, 1, 1, 35, 51, 54, '60,70', 0.04, 80.0, 10, 50, 50, 0, 20, '2.4GHz', 10, 'internal', '["Wyze App (BLE only)"]', 4.0, 8000, 'Wyze Lock Bolt Original Review 2026', 'Wyze Lock Bolt OG. Ultra-budget BLE fingerprint lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='wyze' LIMIT 1), (SELECT id FROM brands WHERE slug='wyze'), 'Wyze Lock Keypad (Accessory)', 'wyze-lock-keypad', 'WYZE-KPD', 'Wireless keypad for Wyze Lock. PIN codes (permanent/scheduled/one-time). Weatherproof. BLE pairing. Coin battery, 12 months. Outdoor mount.', 3000, 'bluetooth', NULL, 0, 'CR2032', 1, 12, 100, '0', 'AES-128', 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, '0', 0.01, 10.0, 10, 50, 0, 0, 0, '2.4GHz', 5, 'internal', '["Wyze Lock"]', 3.8, 3000, 'Wyze Lock Keypad Review 2026', 'Wyze Lock Keypad wireless accessory.');

-- XIAOMI
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='xiaomi' LIMIT 1), (SELECT id FROM brands WHERE slug='xiaomi'), 'Xiaomi Smart Door Lock 2 (WiFi)', 'xiaomi-smart-lock-2', 'XMSL-2', 'WiFi + BLE. Fingerprint + PIN + NFC + HomeKit + key. Push-pull handle. Mi Home app. 8x AA, 12 months. Anti-pry, anti-insert. Door 40-120mm. C-level lock cylinder.', 20000, 'wifi', 'bluetooth', 0, 'AA', 8, 12, 3200, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 120, 0, '0', 0.12, 250.0, 10, 30, 100, 50, 100, '2.4GHz', 20, 'internal', '["Mi Home","Apple HomeKit","Amazon Alexa","Google Assistant"]', 4.2, 5000, 'Xiaomi Smart Lock 2 Review 2026', 'Xiaomi Smart Lock 2. WiFi, HomeKit, push-pull.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='xiaomi' LIMIT 1), (SELECT id FROM brands WHERE slug='xiaomi'), 'Xiaomi Smart Door Lock E10 Budget', 'xiaomi-e10-budget', 'XMSL-E10', 'Budget entry. Fingerprint + PIN + NFC + key. BLE (Mi Home). 4x AA, 12 months. Compact push-pull. Anti-pry alarm. Door 40-65mm. Best-seller budget lock China.', 10000, 'bluetooth', NULL, 0, 'AA', 4, 12, 2200, '0', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 40, 65, 0, '0', 0.06, 120.0, 10, 20, 50, 30, 50, '2.4GHz', 10, 'internal', '["Mi Home"]', 4.0, 10000, 'Xiaomi E10 Budget Lock Review 2026', 'Xiaomi E10 budget fingerprint push-pull lock.');

-- DESSMANN
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='dessmann' LIMIT 1), (SELECT id FROM brands WHERE slug='dessmann'), 'Dessmann Q7FP 3D Face + Cat-Eye Lock', 'dessmann-q7fp-face', 'Q7FP', '3D face + fingerprint + PIN + IC card + key. WiFi. Cat-eye proof. Anti-pry alarm. Push-pull. 5000mAh Li-ion. Door 40-120mm.', 50000, 'wifi', 'bluetooth', 0, 'lithium-ion', 1, 6, 3800, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 120, 0, '0', 0.15, 400.0, 10, 30, 100, 50, 100, '2.4GHz', 20, 'internal', '["Dessmann App"]', 4.3, 800, 'Dessmann Q7FP Face Lock Review 2026', 'Dessmann Q7FP 3D face recognition premium lock.');

-- EUFY
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='eufy' LIMIT 1), (SELECT id FROM brands WHERE slug='eufy'), 'Eufy Smart Lock S12 Pro WiFi', 'eufy-s12-pro-wifi', 'T8510', 'WiFi + BLE. Fingerprint (0.3s) + PIN + key. WiFi built-in (no bridge). Alexa + Google. BHMA Grade 3. Auto-lock. IP65. 4x AA, 12 months. No subscription.', 15000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1400, '3', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 50, 50, 0, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","eufy Security App"]', 4.2, 4000, 'Eufy S12 Pro WiFi Review 2026', 'Eufy S12 Pro WiFi fingerprint lock. No subscription.');

-- LEVEL
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='level' LIMIT 1), (SELECT id FROM brands WHERE slug='level'), 'Level Lock+ (Apple Home Key + Matter)', 'level-lock-plus-matter', 'PLUS-MATTER', 'Apple Home Key + Matter. Invisible design (inside deadbolt). BLE + Thread. NFC unlock via iPhone/Watch. Auto-lock. CR2 battery, 12 months. ANSI Grade 1. Works with existing key.', 35000, 'thread', 'bluetooth', 1, 'CR2', 1, 12, 100, '1', 'AES-256', 0, 0, 1, 1, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.02, 30.0, 10, 0, 0, 0, 100, '2.4GHz', 10, 'internal', '["Apple Home","Apple Home Key","Matter","Amazon Alexa","Google Home"]', 4.5, 3000, 'Level Lock+ Matter Review 2026', 'Level Lock+ Apple Home Key, Matter, invisible.');

-- SAMSUNG
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='samsung' LIMIT 1), (SELECT id FROM brands WHERE slug='samsung'), 'Samsung SHP-DR708 WiFi Deadbolt', 'samsung-shp-dr708', 'SHP-DR708', 'WiFi + BLE deadbolt. Fingerprint + PIN + RFID + SmartThings + key. Built-in WiFi. SmartThings native. Bixby. Auto-lock. ANSI Grade 2. 8x AA, 12 months.', 30000, 'wifi', 'bluetooth', 0, 'AA', 8, 12, 2500, '2', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 80, 0, '0', 0.12, 300.0, 10, 50, 100, 100, 100, '2.4GHz', 20, 'internal', '["Samsung SmartThings","Bixby","Amazon Alexa","Google Assistant"]', 4.2, 2000, 'Samsung SHP-DR708 Review 2026', 'Samsung SHP-DR708 WiFi deadbolt, SmartThings.');

-- ULTRALOQ
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='ultraloq' LIMIT 1), (SELECT id FROM brands WHERE slug='ultraloq'), 'Ultraloq Bolt Fingerprint WiFi Deadbolt', 'ultraloq-bolt-fingerprint', 'UL-BOLT-FP', 'WiFi + BLE. Fingerprint + PIN + key. WiFi built-in. BHMA Grade 2. Auto-lock. Anti-peep. IP65. Alexa + Google. 4x AA, 12 months. U-tec app. No bridge needed.', 18000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1400, '2', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.10, 200.0, 10, 50, 50, 0, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","u-tec App"]', 4.1, 3000, 'Ultraloq Bolt Fingerprint Review 2026', 'Ultraloq Bolt fingerprint WiFi deadbolt.');

-- ZKTECO
INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='zkteco' LIMIT 1), (SELECT id FROM brands WHERE slug='zkteco'), 'ZKTeco TL400B Commercial Fingerprint Lock', 'zkteco-tl400b', 'TL400B', 'Commercial-grade. Fingerprint (500) + PIN + RFID + key. Standalone. USB audit trail export. Anti-pry alarm. ANSI Grade 2. 4x AA, 12 months. Zinc alloy.', 20000, 'none', NULL, 0, 'AA', 4, 12, 2000, '2', 'AES-256', 1, 1, 1, 0, 0, 0, 1, 1, 1, 40, 80, 0, '0', 0.06, 150.0, 50, 50, 500, 100, 0, 'none', 0, 'none', '[]', 4.0, 1500, 'ZKTeco TL400B Review 2026', 'ZKTeco TL400B commercial fingerprint lock.');

-- Tags Batch F-H
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'fingerprint' FROM products WHERE slug IN ('solity-gm6000bkf','switchbot-keypad-touch','tcl-k6p-face','tcl-k2a-budget','teeho-te002w-wifi','veise-ve027-wifi','veise-ks02a-knob','weiser-halo-wifi-fingerprint','wyze-lock-bolt-ble','xiaomi-smart-lock-2','xiaomi-e10-budget','dessmann-q7fp-face','eufy-s12-pro-wifi','samsung-shp-dr708','ultraloq-bolt-fingerprint','zkteco-tl400b');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'wifi' FROM products WHERE slug IN ('solity-wm65-wifi','tcl-k6p-face','teeho-te002w-wifi','veise-ve027-wifi','weiser-halo-wifi-fingerprint','xiaomi-smart-lock-2','dessmann-q7fp-face','eufy-s12-pro-wifi','samsung-shp-dr708','ultraloq-bolt-fingerprint');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'bluetooth' FROM products WHERE slug IN ('switchbot-lock-pro','switchbot-keypad-touch','tcl-k2a-budget','tedee-pro-aluminium','tedee-keypad','teeho-te001-keypad','veise-ks02a-knob','weiser-premis-homekit','wyze-lock-bolt-ble','wyze-lock-keypad','xiaomi-e10-budget');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'thread' FROM products WHERE slug='level-lock-plus-matter';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'matter' FROM products WHERE slug IN ('switchbot-lock-pro','level-lock-plus-matter');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'homekit' FROM products WHERE slug IN ('weiser-premis-homekit','level-lock-plus-matter','xiaomi-smart-lock-2');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'home-key' FROM products WHERE slug='level-lock-plus-matter';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'face-recognition' FROM products WHERE slug IN ('tcl-k6p-face','dessmann-q7fp-face');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'budget' FROM products WHERE slug IN ('teeho-te001-keypad','veise-ks02a-knob','wyze-lock-bolt-ble','wyze-lock-keypad','xiaomi-e10-budget','switchbot-keypad-touch');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'mid' FROM products WHERE slug IN ('solity-wm65-wifi','switchbot-lock-pro','tcl-k2a-budget','tedee-keypad','teeho-te002w-wifi','veise-ve027-wifi','eufy-s12-pro-wifi','ultraloq-bolt-fingerprint','zkteco-tl400b');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'premium' FROM products WHERE slug IN ('solity-gm6000bkf','tedee-pro-aluminium','weiser-halo-wifi-fingerprint','weiser-premis-homekit','tcl-k6p-face','xiaomi-smart-lock-2','dessmann-q7fp-face','level-lock-plus-matter','samsung-shp-dr708');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'apartment' FROM products WHERE slug IN ('solity-gm6000bkf','solity-wm65-wifi','tedee-pro-aluminium');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'smart-home' FROM products WHERE slug IN ('switchbot-lock-pro','xiaomi-smart-lock-2','level-lock-plus-matter','samsung-shp-dr708');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'family' FROM products WHERE slug IN ('teeho-te002w-wifi','veise-ve027-wifi','weiser-halo-wifi-fingerprint','eufy-s12-pro-wifi');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'commercial' FROM products WHERE slug='zkteco-tl400b';
