-- Batch E: SALTO, SMONET, Sesame, Sifely, SimpliSafe (+2 each)

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='salto' LIMIT 1), (SELECT id FROM brands WHERE slug='salto'), 'SALTO Neoxx G3 Wireless Escutcheon', 'salto-neoxx-g3', 'NEOXX-G3', 'Wireless smart escutcheon. BLE + NFC + RFID. JustIN Mobile BLE keys. SVN-Flex network. IP65, IK08. -20 to 60°C outdoor rated. RFID: Mifare, DESFire, NFC. 4x AA, 50000 openings. EN1906 Grade 4.', 35000, 'bluetooth', 'rfid', 0, 'AA', 4, 24, 900, '0', 'AES-128', 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, '0', 0.03, 60.0, 200, 0, 0, 10000, 10000, '13.56MHz', 5, 'internal', '["SALTO Space","JustIN Mobile"]', 4.3, 400, 'SALTO Neoxx G3 Review 2026', 'SALTO Neoxx G3 wireless escutcheon. IP65 outdoor.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='salto' LIMIT 1), (SELECT id FROM brands WHERE slug='salto'), 'SALTO XS4 GEO Cylinder', 'salto-xs4-geo-cylinder', 'XS4-GEO', 'Electronic cylinder with geo-location. BLE mobile keys. Audit trail. Battery in cylinder (CR2 lithium). IP66. No wiring. Retrofit for European doors. SALTO Space/KS compatible.', 25000, 'bluetooth', NULL, 0, 'CR2', 1, 24, 300, '0', 'AES-128', 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, '0', 0.01, 20.0, 50, 0, 0, 5000, 1000, '2.4GHz', 5, 'internal', '["SALTO Space","SALTO KS"]', 4.2, 300, 'SALTO XS4 GEO Cylinder Review 2026', 'SALTO XS4 GEO electronic cylinder. IP66 retrofit.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='smonet' LIMIT 1), (SELECT id FROM brands WHERE slug='smonet'), 'SMONET Y1 Fingerprint + iWatch Lock', 'smonet-y1-iwatch', 'Y1-IW', '7-way: fingerprint (0.3s), app, PIN, iWatch, voice (Alexa/Google via gateway), IC fob, key. G2/G3 gateway for WiFi. Auto-lock. Anti-peep. 4x AA, 12 months.', 8000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1400, '0', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 56, 54, '60,70', 0.06, 120.0, 10, 100, 50, 20, 50, '2.4GHz', 10, 'internal', '["Amazon Alexa (via Gateway)","Google Home (via Gateway)","Apple Watch","TT Lock"]', 4.0, 2000, 'SMONET Y1 Review 2026', 'SMONET Y1 fingerprint + iWatch budget lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='smonet' LIMIT 1), (SELECT id FROM brands WHERE slug='smonet'), 'SMONET WiFi Lever Handle Lock', 'smonet-wifi-lever', 'LVR-WIFI', 'WiFi lever handle. Fingerprint + PIN + app + IC fob + key. Built-in WiFi (no gateway). Alexa+Google. Auto-lock. Reversible. 4x AA, 12 months. Alloy steel. For office/side doors.', 10000, 'wifi', 'bluetooth', 0, 'AA', 4, 12, 1600, '0', 'AES-128', 1, 1, 1, 0, 1, 1, 1, 1, 1, 35, 56, 54, '60,70', 0.10, 200.0, 10, 100, 50, 20, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Home","TT Lock"]', 3.9, 1500, 'SMONET WiFi Lever Review 2026', 'SMONET WiFi lever handle smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='sesame' LIMIT 1), (SELECT id FROM brands WHERE slug='sesame'), 'Sesame Bot 2 Turn Anything Smart', 'sesame-bot-2', 'BOT-2', 'Motorized button/switch pusher. BLE. Controls any physical button, switch, or thumbturn. Can automate existing non-smart deadbolts. 2x CR123A. Candy House ecosystem. NFC tag compatible.', 3000, 'bluetooth', NULL, 0, 'CR123A', 2, 12, 100, '0', 'AES-256', 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, '0', 0.01, 20.0, 10, 0, 0, 0, 100, '2.4GHz', 5, 'internal', '["Sesame 5","Apple HomeKit (via Hub3)","Amazon Alexa"]', 4.0, 2000, 'Sesame Bot 2 Review 2026', 'Sesame Bot 2. Turn any button/switch smart.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='sesame' LIMIT 1), (SELECT id FROM brands WHERE slug='sesame'), 'Sesame Hub3 WiFi + Matter Bridge', 'sesame-hub3', 'HUB3', 'WiFi bridge for Sesame 5 ecosystem. Enables remote control, Matter compatibility, HomeKit, Alexa, Google. Plugs into USB power. Controls up to 3 Sesame devices. 2.4GHz WiFi.', 4000, 'wifi', 'bluetooth', 1, 'USB', 1, 0, 50, '0', 'AES-256', 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, '0', 200.0, 500.0, 100, 0, 0, 0, 100, '2.4GHz', 20, 'internal', '["Apple HomeKit","Amazon Alexa","Google Assistant","Matter"]', 4.1, 1500, 'Sesame Hub3 Review 2026', 'Sesame Hub3 WiFi Matter bridge for Sesame 5.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='sifely' LIMIT 1), (SELECT id FROM brands WHERE slug='sifely'), 'Sifely E Deadbolt Keypad Lock', 'sifely-e-deadbolt', 'SIFELY-E', 'Keypad + BLE app + key. No fingerprint (budget model). 100 timed/one-time/recurring codes. Auto-lock. AES-128. Sifely app. 4x AA, 12 months. For Airbnb/rental.', 6000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1200, '0', 'AES-128', 0, 1, 1, 0, 0, 1, 1, 1, 1, 35, 55, 54, '60,70', 0.06, 100.0, 10, 100, 0, 0, 50, '2.4GHz', 10, 'internal', '["Sifely App"]', 3.8, 2000, 'Sifely E Deadbolt Review 2026', 'Sifely E deadbolt keypad lock for rentals.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='sifely' LIMIT 1), (SELECT id FROM brands WHERE slug='sifely'), 'Sifely WiFi Gateway for Smart Lock', 'sifely-wifi-gateway', 'SIFELY-GW', 'WiFi gateway for Sifely locks. Enables remote access, Alexa/Google voice control. Real-time notifications. 2.4GHz WiFi. USB powered. Pairs with all Sifely locks.', 3000, 'wifi', 'bluetooth', 0, 'USB', 1, 0, 30, '0', 'AES-128', 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, '0', 100.0, 300.0, 100, 0, 0, 0, 50, '2.4GHz', 20, 'internal', '["Amazon Alexa","Google Assistant","Sifely App"]', 3.7, 1500, 'Sifely WiFi Gateway Review 2026', 'Sifely WiFi gateway for remote smart lock control.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='simplisafe' LIMIT 1), (SELECT id FROM brands WHERE slug='simplisafe'), 'SimpliSafe Keypad Entry Smart Lock', 'simplisafe-keypad-entry', 'SS-LOCK-V2', 'Slim deadbolt without separate PIN pad. Built-in keypad on interior. Integrates with SimpliSafe security system. Auto-lock when armed. 4x AA, 12 months. Alexa + Google.', 15000, 'wifi', NULL, 0, 'AA', 4, 12, 1300, '0', 'AES-128', 0, 1, 1, 0, 1, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.08, 150.0, 10, 30, 0, 0, 50, '2.4GHz', 20, 'internal', '["SimpliSafe Security","Amazon Alexa","Google Assistant"]', 4.0, 2500, 'SimpliSafe Keypad Entry Lock Review 2026', 'SimpliSafe keypad entry smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='simplisafe' LIMIT 1), (SELECT id FROM brands WHERE slug='simplisafe'), 'SimpliSafe Wireless PIN Pad (Standalone)', 'simplisafe-wireless-pin-pad', 'SS-KPD', 'Wireless keypad companion for SimpliSafe Lock. Weatherproof. Backlit. Duress PIN. Coin battery, 2 years. Outdoor mount. Works with any SimpliSafe smart lock.', 5000, 'wifi', NULL, 0, 'CR2032', 1, 24, 120, '0', 'AES-128', 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, '0', 0.01, 10.0, 10, 50, 0, 0, 0, '2.4GHz', 10, 'internal', '["SimpliSafe Security"]', 3.9, 2000, 'SimpliSafe Wireless PIN Pad Review 2026', 'SimpliSafe wireless PIN pad accessory.');

-- Tags Batch E
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'bluetooth' FROM products WHERE slug IN ('salto-neoxx-g3','salto-xs4-geo-cylinder','smonet-y1-iwatch','sesame-bot-2','sifely-e-deadbolt');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'wifi' FROM products WHERE slug IN ('smonet-wifi-lever','sesame-hub3','sifely-wifi-gateway','simplisafe-keypad-entry','simplisafe-wireless-pin-pad');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'fingerprint' FROM products WHERE slug IN ('smonet-y1-iwatch','smonet-wifi-lever');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'keypad' FROM products WHERE slug IN ('sifely-e-deadbolt','simplisafe-keypad-entry','simplisafe-wireless-pin-pad');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'matter' FROM products WHERE slug='sesame-hub3';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'budget' FROM products WHERE slug IN ('sesame-bot-2','sesame-hub3','sifely-e-deadbolt','sifely-wifi-gateway','simplisafe-wireless-pin-pad','smonet-y1-iwatch');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'mid' FROM products WHERE slug IN ('salto-xs4-geo-cylinder','smonet-wifi-lever','simplisafe-keypad-entry');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'premium' FROM products WHERE slug='salto-neoxx-g3';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'commercial' FROM products WHERE slug IN ('salto-neoxx-g3','salto-xs4-geo-cylinder');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'rental' FROM products WHERE slug IN ('sifely-e-deadbolt','smonet-wifi-lever');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'apartment' FROM products WHERE slug IN ('sesame-bot-2','simplisafe-keypad-entry');
