-- Batch C: Hornbill, Häfele, Kaadas, Latch, Mul-T-Lock (+2 each)

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='hornbill' LIMIT 1), (SELECT id FROM brands WHERE slug='hornbill'), 'Hornbill Y4 Smart Lever Handle Lock', 'hornbill-y4-lever', 'Y4-LVR', 'Lever handle. Fingerprint (100) + PIN (300) + IC card + BLE app + key. Auto-lock. Anti-peep. Reversible left/right. BHMA Grade 3. 4x AA, 12 months. Zinc alloy.', 7000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1600, '3', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.06, 120.0, 10, 300, 100, 50, 50, '2.4GHz', 10, 'internal', '["Hornbill App"]', 3.9, 2000, 'Hornbill Y4 Lever Review 2026', 'Hornbill Y4 lever handle smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='hornbill' LIMIT 1), (SELECT id FROM brands WHERE slug='hornbill'), 'Hornbill A4-BBF Biometric Deadbolt', 'hornbill-a4-bbf', 'A4-BBF', 'Biometric deadbolt. Fingerprint + PIN + BLE app + key. No WiFi (Bluetooth only). Budget offline smart lock. Auto-lock. USB-C emergency. 4x AA. BHMA Grade 3.', 5000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1200, '3', 'AES-128', 1, 1, 1, 0, 0, 0, 1, 1, 1, 35, 51, 54, '60,70', 0.04, 80.0, 10, 100, 50, 0, 20, '2.4GHz', 10, 'internal', '["Hornbill App"]', 3.8, 3000, 'Hornbill A4-BBF Review 2026', 'Hornbill A4-BBF budget biometric deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='hafele' LIMIT 1), (SELECT id FROM brands WHERE slug='hafele'), 'Häfele EL9500 3D Face Recognition Lock', 'hafele-el9500-face', 'EL9500', '3D structured-light face recognition + fingerprint + PIN + RFID + app + key. Push-pull handle. WiFi remote. Cat-eye proof. Anti-pry alarm. 8x AA, 12 months. Door 40-100mm.', 50000, 'wifi', 'bluetooth', 0, 'AA', 8, 12, 3800, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 100, 0, '0', 0.15, 400.0, 10, 30, 50, 50, 100, '2.4GHz', 20, 'internal', '["Hafele App","Amazon Alexa"]', 4.2, 500, 'Häfele EL9500 Face Lock Review 2026', 'Häfele EL9500 3D face recognition push-pull lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='hafele' LIMIT 1), (SELECT id FROM brands WHERE slug='hafele'), 'Häfele DL7600 Hotel RFID Lock', 'hafele-dl7600-hotel', 'DL7600', 'Mortise RFID hotel lock. Mifare card + mechanical key override. PMS integration. ANSI Grade 1 mortise. Stainless steel. 4x AA, 15000 openings. Door 38-55mm.', 25000, 'rfid', NULL, 0, 'AA', 4, 18, 2200, '1', 'AES-128', 0, 0, 1, 0, 0, 0, 0, 1, 1, 38, 55, 0, '0', 0.02, 50.0, 100, 0, 0, 5000, 0, '13.56MHz', 5, 'internal', '["Hafele Hotel System"]', 4.1, 300, 'Häfele DL7600 Hotel Review 2026', 'Häfele DL7600 hotel RFID lock ANSI Grade 1.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='kaadas' LIMIT 1), (SELECT id FROM brands WHERE slug='kaadas'), 'Kaadas K20 Pro Max 3D Face Lock', 'kaadas-k20-pro-max', 'K20-PRO-MAX', '3D structured-light face recognition. Fingerprint + PIN + IC card + app + key. WiFi remote. Cat-eye proof. 5050mAh Li-ion, 6 months. Push-pull. Anti-pry alarm. Door 40-120mm.', 45000, 'wifi', 'bluetooth', 0, 'lithium-ion', 1, 6, 3500, '0', 'AES-256', 1, 1, 1, 0, 1, 1, 1, 1, 1, 40, 120, 0, '0', 0.15, 350.0, 10, 30, 100, 50, 100, '2.4GHz', 20, 'internal', '["Kaadas App","Amazon Alexa"]', 4.3, 1000, 'Kaadas K20 Pro Max Review 2026', 'Kaadas K20 Pro Max 3D face recognition WiFi lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='kaadas' LIMIT 1), (SELECT id FROM brands WHERE slug='kaadas'), 'Kaadas S110 Budget Fingerprint Deadbolt', 'kaadas-s110', 'S110', 'Budget fingerprint deadbolt. Fingerprint (50) + PIN + IC card + key. BLE app. Auto-lock. ANSI Grade 3. 4x AA, 12 months. Zinc alloy.', 12000, 'bluetooth', NULL, 0, 'AA', 4, 12, 1400, '3', 'AES-128', 1, 1, 1, 0, 0, 1, 1, 1, 1, 35, 51, 54, '60,70', 0.06, 100.0, 10, 50, 50, 30, 20, '2.4GHz', 10, 'internal', '["Kaadas App"]', 4.0, 2000, 'Kaadas S110 Review 2026', 'Kaadas S110 budget fingerprint deadbolt.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='latch' LIMIT 1), (SELECT id FROM brands WHERE slug='latch'), 'Latch C2 Commercial Cylindrical Lock', 'latch-c2-cylindrical', 'C2', 'Commercial cylindrical knob lock. ANSI Grade 1. BLE + NFC. Latch Manager cloud. DOOR App, NFC keycard, doorcode. 6x AA, 2 years. ADA compliant. -30°C to 70°C. Offline-first.', 35000, 'bluetooth', 'nfc', 0, 'AA', 6, 24, 2000, '1', 'AES-256', 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, '0', 0.04, 80.0, 100, 100, 0, 1000, 1000, '13.56MHz', 5, 'internal', '["Latch Manager Cloud","DOOR App"]', 4.3, 200, 'Latch C2 Review 2026', 'Latch C2 commercial cylindrical smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='latch' LIMIT 1), (SELECT id FROM brands WHERE slug='latch'), 'Latch R2 Commercial Retrofit', 'latch-r2-retrofit', 'R2', 'Retrofit for existing deadbolts. Commercial grade. BLE + NFC. Latch Manager cloud. Smart visitor management. 6x AA, 2 years. ADA compliant. For multifamily buildings.', 30000, 'bluetooth', 'nfc', 0, 'AA', 6, 24, 800, '0', 'AES-256', 0, 0, 1, 1, 0, 1, 1, 1, 1, 35, 51, 0, '0', 0.04, 80.0, 100, 50, 0, 500, 500, '13.56MHz', 5, 'internal', '["Latch Manager Cloud","DOOR App"]', 4.2, 150, 'Latch R2 Retrofit Review 2026', 'Latch R2 commercial retrofit smart lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='mul-t-lock' LIMIT 1), (SELECT id FROM brands WHERE slug='mul-t-lock'), 'Mul-T-Lock ENTR Bluetooth Only', 'multlock-entr-bt', 'ENTR-BT', 'Basic ENTR motorized cylinder. BLE only. App control. Auto-lock. Rechargeable Li-ion. No drilling. IP44. 3-year warranty. Entry-level high-security smart lock.', 30000, 'bluetooth', NULL, 0, 'lithium-ion', 1, 12, 500, '0', 'AES-128', 0, 0, 1, 0, 0, 1, 1, 1, 1, 35, 78, 0, '0', 0.04, 80.0, 10, 20, 0, 0, 20, '2.4GHz', 10, 'internal', '["Mul-T-Lock ENTR App"]', 4.1, 300, 'Mul-T-Lock ENTR BT Review 2026', 'Mul-T-Lock ENTR Bluetooth motorized cylinder lock.');

INSERT INTO products (series_id, brand_id, name, slug, model_number, description, price_usd, protocol, secondary_protocol, supports_matter, battery_type, battery_count, battery_life_months, weight_grams, ansi_grade, encryption_type, has_fingerprint, has_keypad, has_auto_lock, has_auto_unlock, has_voice_control, has_remote_access, has_guest_codes, has_activity_log, has_physical_key, door_thickness_min_mm, door_thickness_max_mm, bore_diameter_mm, backset_mm, standby_power_mw, active_power_mw, operations_per_day, max_pin_codes, max_fingerprints, max_cards, max_app_users, rf_frequency, rf_range_meters, antenna_type, ecosystems_json, rating, review_count, meta_title, meta_description) VALUES
((SELECT ps.id FROM product_series ps JOIN brands b ON ps.brand_id=b.id WHERE b.slug='mul-t-lock' LIMIT 1), (SELECT id FROM brands WHERE slug='mul-t-lock'), 'Mul-T-Lock CLIQ Go Digital Cylinder', 'multlock-cliq-go', 'CLIQ-GO', 'Digital cylinder with mobile key. BLE. Audit trail. No wiring, battery in key. Mul-T-Lock high-security core. IP67 weatherproof. -25°C to 65°C. Commercial/industrial use.', 35000, 'bluetooth', NULL, 0, 'CR2', 1, 24, 250, '0', 'AES-256', 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, '0', 0.01, 10.0, 50, 100, 0, 0, 100, '2.4GHz', 5, 'internal', '["CLIQ Go App"]', 4.4, 200, 'Mul-T-Lock CLIQ Go Review 2026', 'Mul-T-Lock CLIQ Go digital cylinder. IP67 commercial.');

-- Tags Batch C
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'bluetooth' FROM products WHERE slug IN ('hornbill-y4-lever','hornbill-a4-bbf','kaadas-s110','latch-c2-cylindrical','latch-r2-retrofit','multlock-entr-bt','multlock-cliq-go');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'wifi' FROM products WHERE slug IN ('hafele-el9500-face','kaadas-k20-pro-max');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'protocol', 'rfid' FROM products WHERE slug='hafele-dl7600-hotel';
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'fingerprint' FROM products WHERE slug IN ('hornbill-y4-lever','hornbill-a4-bbf','hafele-el9500-face','kaadas-k20-pro-max','kaadas-s110');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'face-recognition' FROM products WHERE slug IN ('hafele-el9500-face','kaadas-k20-pro-max');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'feature', 'keypad' FROM products WHERE slug IN ('hornbill-y4-lever','kaadas-s110','latch-c2-cylindrical');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'budget' FROM products WHERE slug IN ('hornbill-y4-lever','hornbill-a4-bbf','kaadas-s110');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'premium' FROM products WHERE slug IN ('hafele-el9500-face','kaadas-k20-pro-max','latch-c2-cylindrical','multlock-cliq-go');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'price_tier', 'mid' FROM products WHERE slug IN ('hafele-dl7600-hotel','latch-r2-retrofit','multlock-entr-bt');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'commercial' FROM products WHERE slug IN ('latch-c2-cylindrical','latch-r2-retrofit','multlock-cliq-go','hafele-dl7600-hotel');
INSERT INTO product_tags (product_id, tag_type, tag_value) SELECT id, 'scenario', 'family' FROM products WHERE slug IN ('hornbill-y4-lever','kaadas-k20-pro-max','kaadas-s110');
