/**
 * 文章注册表 - 所有文章的元数据索引
 * 从旧站点迁移的硬编码文章
 * 自动生成于: 2026-02-15T14:30:00.000Z
 * 总文章数: 49
 */

import { ArticleMetadata } from './types';

export const articleRegistry: Record<string, ArticleMetadata> = {

  // ==================== GUIDES ====================
  'complete-troubleshooting-guide': {
    slug: 'complete-troubleshooting-guide',
    title: "Smart Lock Troubleshooting Guide: Fix 95% of Issues in 5 Minutes",
    description: "Complete step-by-step troubleshooting guide for smart lock problems. Covers battery issues, connection problems, mechanical failures, authentication errors, firmware bugs, and when to call support. Includes diagnostic decision trees, error code explanations, and real-world solutions from 10,000+ support cases.",
    category: 'guides',
    pubDate: '2024-02-26',
    wordCount: 5800,
    readingTime: 23,
    keywords: ["smart lock not working", "smart lock troubleshooting", "fix smart lock battery", "smart lock will not connect", "smart lock stuck", "PIN code not working"],
    tags: ["troubleshooting", "support", "fix", "battery", "connectivity", "mechanical"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["maintenance-troubleshooting-guide", "credential-management-best-practices"],
    relatedTools: ["diagnostic-tool", "error-code-lookup"],
    updatedAt: '2026-02-15',
  },
  'disaster-recovery-business-continuity': {
    slug: 'disaster-recovery-business-continuity',
    title: "Smart Lock Disaster Recovery & Business Continuity: Complete DR/BC Planning",
    description: "Comprehensive disaster recovery and business continuity guide for smart lock systems. Includes business impact analysis, FMEA, high availability architecture, RTO/RPO targets, failover mechanisms, backup strategies, disaster scenario response plans, and ISO 22301 compliance framework.",
    category: 'guides',
    pubDate: '2024-02-03',
    wordCount: 5400,
    readingTime: 22,
    keywords: ["smart lock disaster recovery", "business continuity access control", "high availability smart locks", "RTO RPO smart locks", "failover mechanisms", "backup recovery strategy"],
    tags: ["disaster-recovery", "business-continuity", "high-availability", "backup-recovery", "iso-22301"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["maintenance-troubleshooting-guide", "project-implementation-deployment-guide", "offline-capability-design"],
    relatedTools: ["bia-calculator", "rto-rpo-planner", "failover-tester"],
    updatedAt: '2026-02-15',
  },
  'door-compatibility-guide': {
    slug: 'door-compatibility-guide',
    title: "Smart Lock Door Compatibility Guide: Measurements, Standards, and Installation",
    description: "Complete guide to smart lock door compatibility. Learn how to measure door thickness, backset, cross bore, and navigate US, European, and Asian lock standards to ensure your smart lock fits perfectly.",
    category: 'guides',
    pubDate: '2024-01-27',
    wordCount: 3200,
    readingTime: 13,
    keywords: ["smart lock compatibility", "will smart lock fit my door", "door lock measurements", "smart lock door requirements", "retrofit smart lock", "mortise vs deadbolt"],
    tags: ["compatibility", "installation", "measurements", "standards"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["smart-lock-protocols-overview", "complete-troubleshooting-guide", "smart-lock-pairing-complete-guide", "smart-lock-battery-life-guide", "long-term-rental-strategy"],
    relatedTools: ["door-lock-compatibility-checker", "protocol-selection-wizard"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-pairing-complete-guide': {
    slug: 'smart-lock-pairing-complete-guide',
    title: "Smart Lock Pairing: Complete 2026 Troubleshooting Guide",
    description: "Comprehensive guide to pairing smart locks with hubs and apps. Step-by-step pairing procedures, troubleshooting hub discovery failures, signal optimization, and protocol-specific solutions.",
    category: 'guides',
    pubDate: '2024-11-22',
    wordCount: 4000,
    readingTime: 16,
    keywords: ["pair smart lock", "smart lock not pairing", "hub cant find lock", "zigbee pairing", "zwave pairing"],
    tags: ["pairing", "troubleshooting", "setup"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'add-fingerprint-to-lock': {
    slug: 'add-fingerprint-to-lock',
    title: "How to Add Fingerprint to Smart Lock - Complete Enrollment Guide",
    description: "Add fingerprint to smart lock for biometric access. Step-by-step enrollment, proper scanning technique, multiple finger setup, and troubleshooting enrollment failures.",
    category: 'guides',
    pubDate: '2024-04-01',
    wordCount: 750,
    readingTime: 4,
    keywords: ["add fingerprint", "enroll fingerprint", "fingerprint setup", "biometric enrollment", "scan fingerprint"],
    tags: ["fingerprint", "biometric", "setup", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["fingerprint-not-recognized", "how-to-add-user-code"],
    updatedAt: '2026-02-15',
  },
  'change-master-code': {
    slug: 'change-master-code',
    title: "How to Change Smart Lock Master Code - Security Guide",
    description: "Change master code on smart lock for security. Step-by-step process, when to change, password best practices, and protect against unauthorized access for all lock brands.",
    category: 'guides',
    pubDate: '2024-03-25',
    wordCount: 800,
    readingTime: 4,
    keywords: ["change master code", "update master PIN", "reset master code", "change admin code", "smart lock password"],
    tags: ["security", "master-code", "password"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["forgot-master-code-reset", "secure-smart-lock-best-practices", "how-to-add-user-code"],
    updatedAt: '2026-02-15',
  },
  'create-temporary-guest-code': {
    slug: 'create-temporary-guest-code',
    title: "How to Create Temporary Guest Code for Smart Lock",
    description: "Create time-limited PIN codes for guests, contractors, and one-time access. Set precise start/end times, avoid common expiration mistakes, and manage temporary access securely.",
    category: 'guides',
    pubDate: '2024-03-02',
    wordCount: 950,
    readingTime: 4,
    keywords: ["temporary guest code", "time limited PIN", "guest access code", "temporary smart lock code", "airbnb guest code"],
    tags: ["guest-access", "temporary-code", "user-management", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["how-to-add-user-code", "smart-locks-airbnb-guide"],
    updatedAt: '2026-02-15',
  },
  'delete-smart-lock-user': {
    slug: 'delete-smart-lock-user',
    title: "How to Delete or Remove User from Smart Lock",
    description: "Remove user access from smart lock. Delete PIN codes, revoke app access, remove expired guests, and manage user permissions safely for all smart lock brands.",
    category: 'guides',
    pubDate: '2024-03-09',
    wordCount: 850,
    readingTime: 4,
    keywords: ["delete smart lock user", "remove access code", "revoke smart lock access", "delete PIN code", "remove guest access"],
    tags: ["user-management", "security", "access-control"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["how-to-add-user-code", "create-temporary-guest-code"],
    updatedAt: '2026-02-15',
  },
  'fingerprint-not-recognized': {
    slug: 'fingerprint-not-recognized',
    title: "Smart Lock Fingerprint Not Recognized - Fix Biometric Issues",
    description: "Fix fingerprint recognition failures on smart locks. Re-enroll fingers, clean sensor, optimize scan technique, and troubleshoot biometric authentication for reliable access.",
    category: 'guides',
    pubDate: '2024-03-22',
    wordCount: 850,
    readingTime: 4,
    keywords: ["fingerprint not working", "biometric failed", "fingerprint scanner", "cannot scan finger", "fingerprint unlock failed"],
    tags: ["fingerprint", "biometric", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-code-not-working", "clean-maintain-smart-lock"],
    updatedAt: '2026-02-15',
  },
  'forgot-master-code-reset': {
    slug: 'forgot-master-code-reset',
    title: "Forgot Smart Lock Master Code - How to Reset and Regain Access",
    description: "Reset smart lock when you forgot master code or PIN. Factory reset methods, regain access through app, backup key usage, and prevent future lockouts for all smart lock brands.",
    category: 'guides',
    pubDate: '2024-03-06',
    wordCount: 900,
    readingTime: 4,
    keywords: ["forgot smart lock code", "reset master code", "forgot PIN code", "smart lock factory reset", "regain access smart lock"],
    tags: ["emergency", "master-code", "reset"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["emergency-battery-died-locked-out", "smart-lock-code-not-working"],
    updatedAt: '2026-02-15',
  },
  'how-to-add-user-code': {
    slug: 'how-to-add-user-code',
    title: "How to Add New User Code to Smart Lock",
    description: "Step-by-step guide to add new PIN codes and users to your smart lock. Set permanent or temporary codes, manage access schedules, and verify successful setup for all lock brands.",
    category: 'guides',
    pubDate: '2024-03-01',
    wordCount: 900,
    readingTime: 4,
    keywords: ["add smart lock user", "create PIN code", "add user to smart lock", "set up access code", "program smart lock code"],
    tags: ["user-management", "PIN-code", "access-control", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-locks-airbnb-guide", "smart-lock-code-not-working"],
    updatedAt: '2026-02-15',
  },
  'improve-auto-lock-reliability': {
    slug: 'improve-auto-lock-reliability',
    title: "How to Improve Auto-Lock Reliability - Stop Failed Auto-Locks",
    description: "Fix unreliable auto-lock. Troubleshoot delayed auto-lock, failed automatic locking, prevent false triggers, and ensure door locks automatically every time.",
    category: 'guides',
    pubDate: '2024-04-06',
    wordCount: 700,
    readingTime: 4,
    keywords: ["auto-lock not working", "automatic lock fails", "auto-lock unreliable", "delayed auto-lock", "improve auto-lock"],
    tags: ["auto-lock", "automation", "reliability"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["set-up-lock-automations", "smart-lock-shows-wrong-status"],
    updatedAt: '2026-02-15',
  },
  'lock-auto-relocks-immediately': {
    slug: 'lock-auto-relocks-immediately',
    title: "Lock Auto-Relocks Immediately After Unlock - Stop Instant Relock",
    description: "Fix smart lock that relocks immediately after unlocking. Disable auto-lock temporarily, adjust timeout, fix sensor issues, and stop annoying instant relock behavior.",
    category: 'guides',
    pubDate: '2024-04-16',
    wordCount: 600,
    readingTime: 3,
    keywords: ["auto relock", "instant relock", "locks immediately", "won't stay unlocked", "auto lock problem"],
    tags: ["auto-lock", "troubleshooting", "automation"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["improve-auto-lock-reliability", "set-up-lock-automations"],
    updatedAt: '2026-02-15',
  },
  'lock-motor-noise-troubleshooting': {
    slug: 'lock-motor-noise-troubleshooting',
    title: "Smart Lock Motor Noise - Diagnose and Fix Grinding Sounds",
    description: "Fix loud smart lock motor. Troubleshoot grinding, whirring, clicking sounds. Diagnose motor wear, alignment issues, and restore quiet operation.",
    category: 'guides',
    pubDate: '2024-04-11',
    wordCount: 650,
    readingTime: 3,
    keywords: ["motor noise", "grinding sound", "loud motor", "clicking noise", "motor problem"],
    tags: ["motor", "noise", "mechanical"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-making-noise", "smart-lock-wont-lock-unlock-completely"],
    updatedAt: '2026-02-15',
  },
  'lock-unresponsive-after-firmware-update': {
    slug: 'lock-unresponsive-after-firmware-update',
    title: "Smart Lock Unresponsive After Firmware Update - Recovery Guide",
    description: "Fix smart lock that stopped working after firmware update. Recover from failed updates, restore functionality, and prevent future update issues for all lock brands.",
    category: 'guides',
    pubDate: '2024-03-26',
    wordCount: 750,
    readingTime: 4,
    keywords: ["firmware update failed", "lock broken after update", "update bricked lock", "unresponsive after update", "firmware recovery"],
    tags: ["firmware", "recovery", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["update-smart-lock-firmware", "forgot-master-code-reset"],
    updatedAt: '2026-02-15',
  },
  'share-access-securely': {
    slug: 'share-access-securely',
    title: "How to Share Smart Lock Access Securely - Safe User Management",
    description: "Share smart lock access safely. Temporary codes, time limits, access levels, revoke permissions, and best practices for secure access sharing with family, guests, and service providers.",
    category: 'guides',
    pubDate: '2024-04-05',
    wordCount: 750,
    readingTime: 4,
    keywords: ["share access", "grant access", "temporary access", "secure sharing", "access management"],
    tags: ["access", "security", "sharing", "user-management"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["create-temporary-guest-code", "secure-smart-lock-best-practices", "delete-smart-lock-user"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-code-not-working': {
    slug: 'smart-lock-code-not-working',
    title: "Smart Lock Code/PIN Not Working - Instant Fix Guide",
    description: "Fix smart lock PIN codes that won't work. Troubleshoot incorrect codes, expired access, keypad issues, and user management problems. Works for Yale, Schlage, Kwikset, August locks.",
    category: 'guides',
    pubDate: '2024-02-24',
    wordCount: 1050,
    readingTime: 5,
    keywords: ["smart lock code not working", "PIN won't unlock door", "keypad code rejected", "smart lock PIN failed", "access code not working"],
    tags: ["keypad", "PIN-code", "access-control"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["complete-troubleshooting-guide", "smart-locks-airbnb-complete-guide"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-shows-wrong-status': {
    slug: 'smart-lock-shows-wrong-status',
    title: "Smart Lock Shows Wrong Status - Fix Sync Issues",
    description: "Fix smart lock showing incorrect status in app. Troubleshoot locked vs unlocked display errors, sync issues, and ensure accurate status reporting for all lock brands.",
    category: 'guides',
    pubDate: '2024-03-14',
    wordCount: 850,
    readingTime: 4,
    keywords: ["wrong lock status", "lock status not updating", "shows unlocked but locked", "status sync error", "lock status incorrect"],
    tags: ["status", "sync", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-keeps-going-offline", "improve-connection-stability"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-wont-lock-unlock-completely': {
    slug: 'smart-lock-wont-lock-unlock-completely',
    title: "Smart Lock Won't Lock or Unlock Completely - Partial Extension Fix",
    description: "Fix smart lock that doesn't fully extend or retract deadbolt. Troubleshoot partial locking, incomplete throw, motor issues, and restore full lock/unlock operation.",
    category: 'guides',
    pubDate: '2024-03-31',
    wordCount: 750,
    readingTime: 4,
    keywords: ["won't lock completely", "partial lock", "deadbolt doesn't extend", "incomplete unlock", "lock halfway"],
    tags: ["mechanical", "motor", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-jammed-wont-turn", "smart-lock-making-noise"],
    updatedAt: '2026-02-15',
  },

  // ==================== USE CASES ====================
  'enterprise-commercial-deployment': {
    slug: 'enterprise-commercial-deployment',
    title: "Enterprise Smart Lock Deployment: Complete 2026 Guide",
    description: "Comprehensive guide for deploying smart locks in commercial buildings, schools, healthcare facilities, and government offices. Multi-unit planning, access management, integration, and ROI analysis.",
    category: 'use-cases',
    pubDate: '2024-11-22',
    wordCount: 4000,
    readingTime: 16,
    keywords: ["commercial smart locks", "enterprise access control", "multi-unit smart locks", "building smart locks"],
    tags: ["enterprise", "commercial", "multi-property"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'long-term-rental-property-strategy': {
    slug: 'long-term-rental-property-strategy',
    title: "Smart Locks for Long-Term Rental Properties: ROI & Operational Strategy",
    description: "Comprehensive guide for landlords and property managers implementing smart locks across rental portfolios. Includes TCO analysis, tenant lifecycle automation, legal compliance, turnover optimization, and real-world ROI data from 1-500+ unit deployments.",
    category: 'use-cases',
    pubDate: '2024-02-10',
    wordCount: 4800,
    readingTime: 19,
    keywords: ["smart lock rental property", "landlord smart lock benefits", "rental property automation", "tenant turnover efficiency", "property management smart locks", "rental property ROI smart locks"],
    tags: ["rental-property", "landlord", "property-management", "roi-analysis", "tenant-turnover"],
    isPillar: false,
    isSupport: false,
    featured: true,
    relatedArticles: ["multi-unit-buildings", "credential-management-best-practices", "office-access-control"],
    relatedTools: ["rental-roi-calculator", "turnover-time-estimator"],
    updatedAt: '2026-02-15',
  },
  'long-term-rental-strategy': {
    slug: 'long-term-rental-strategy',
    title: "Smart Locks for Long-Term Rentals: Complete 2026 Guide",
    description: "Comprehensive strategy for landlords managing long-term rental properties with smart locks. Tenant management, access control, maintenance automation, and multi-property scaling tactics.",
    category: 'use-cases',
    pubDate: '2024-11-22',
    wordCount: 3500,
    readingTime: 14,
    keywords: ["rental property smart locks", "landlord smart locks", "long term rental locks"],
    tags: ["rentals", "landlords", "property-management"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'smart-locks-airbnb-complete-guide': {
    slug: 'smart-locks-airbnb-complete-guide',
    title: "Smart Locks for Airbnb: Complete 2026 Investment Guide",
    description: "Comprehensive guide to smart locks for short-term rentals. ROI analysis, lock selection criteria, guest access automation, PMS integration, and operational strategies for Airbnb hosts.",
    category: 'use-cases',
    pubDate: '2024-11-22',
    wordCount: 4500,
    readingTime: 18,
    keywords: ["airbnb smart lock", "vacation rental smart lock", "airbnb keyless entry", "short term rental locks"],
    tags: ["airbnb", "vacation-rental", "str", "automation"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },

  // ==================== PROTOCOLS ====================
  'smart-lock-protocols-overview': {
    slug: 'smart-lock-protocols-overview',
    title: "Smart Lock Protocols: Complete 2026 Technical Overview",
    description: "Comprehensive guide to WiFi, Zigbee, Z-Wave, Thread, and Matter protocols for smart locks. Technical architecture, battery life comparison, security analysis, and protocol selection framework.",
    category: 'protocols',
    pubDate: '2024-11-22',
    wordCount: 5200,
    readingTime: 21,
    keywords: ["smart lock protocols", "wifi vs zigbee smart lock", "z-wave smart lock", "matter smart lock"],
    tags: ["protocols", "wifi", "zigbee", "z-wave", "thread", "matter"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'zigbee-vs-zwave-comparison': {
    slug: 'zigbee-vs-zwave-comparison',
    title: "Zigbee vs Z-Wave Smart Locks: Complete 2026 Comparison",
    description: "Detailed technical comparison of Zigbee and Z-Wave protocols for smart locks. Frequency analysis, mesh networking, battery life, compatibility, and real-world performance data to choose the best protocol.",
    category: 'protocols',
    pubDate: '2024-11-22',
    wordCount: 3500,
    readingTime: 14,
    keywords: ["zigbee vs zwave", "zigbee zwave comparison", "zwave vs zigbee locks"],
    tags: ["zigbee", "zwave", "comparison"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'command-timeout-errors': {
    slug: 'command-timeout-errors',
    title: "Smart Lock Command Timeout - Fix Slow or Failed Commands",
    description: "Fix smart lock command timeouts. Troubleshoot slow response, failed lock/unlock commands, communication delays, and restore reliable command execution.",
    category: 'protocols',
    pubDate: '2024-04-08',
    wordCount: 700,
    readingTime: 4,
    keywords: ["command timeout", "command failed", "timeout error", "slow commands", "unresponsive lock"],
    tags: ["timeout", "performance", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-response-slow", "smart-lock-no-response", "improve-connection-stability"],
    updatedAt: '2026-02-15',
  },
  'connect-lock-to-homekit': {
    slug: 'connect-lock-to-homekit',
    title: "How to Connect Smart Lock to HomeKit - Complete Setup Guide",
    description: "Step-by-step guide to add smart lock to Apple HomeKit. Scan HomeKit code, troubleshoot pairing failures, set up automations, and integrate with Home app.",
    category: 'protocols',
    pubDate: '2024-03-20',
    wordCount: 900,
    readingTime: 4,
    keywords: ["homekit smart lock", "add lock to homekit", "homekit setup", "apple home lock", "homekit pairing"],
    tags: ["homekit", "apple", "setup", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-home-platform-integration", "pair-smart-lock-with-hub"],
    updatedAt: '2026-02-15',
  },
  'improve-connection-stability': {
    slug: 'improve-connection-stability',
    title: "How to Improve Smart Lock Connection Stability",
    description: "Stop smart lock disconnections and improve reliability. Optimize mesh network, eliminate interference, strengthen signal, and prevent offline issues with proven techniques.",
    category: 'protocols',
    pubDate: '2024-03-08',
    wordCount: 950,
    readingTime: 4,
    keywords: ["improve smart lock connection", "stop disconnections", "smart lock reliability", "stable connection", "prevent offline"],
    tags: ["connectivity", "stability", "optimization"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-keeps-going-offline", "rf-mesh-network-planning", "maximize-smart-lock-battery-life"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-disconnects-after-power-outage': {
    slug: 'smart-lock-disconnects-after-power-outage',
    title: "Smart Lock Disconnects After Power Outage - Quick Recovery",
    description: "Reconnect smart lock after power outage. Fix hub offline issues, restore mesh network, prevent future disconnections, and ensure reliable post-outage recovery.",
    category: 'protocols',
    pubDate: '2024-03-21',
    wordCount: 800,
    readingTime: 4,
    keywords: ["power outage lock", "lock offline after outage", "restore after power loss", "hub offline", "reconnect lock"],
    tags: ["power-outage", "recovery", "connectivity"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-keeps-going-offline", "improve-connection-stability"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-keeps-going-offline': {
    slug: 'smart-lock-keeps-going-offline',
    title: "Smart Lock Keeps Going Offline - Fix Disconnection Issues",
    description: "Fix smart lock that repeatedly goes offline. Diagnose signal strength, mesh network, interference issues and improve connection reliability.",
    category: 'protocols',
    pubDate: '2024-03-09',
    wordCount: 1100,
    readingTime: 5,
    keywords: ["smart lock offline", "lock disconnecting", "won't stay connected"],
    tags: ["connectivity", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["improve-connection-stability", "complete-troubleshooting-guide"],
    updatedAt: '2026-02-15',
  },

  // ==================== SECURITY ====================
  'data-privacy-compliance-guide': {
    slug: 'data-privacy-compliance-guide',
    title: "Smart Lock Data Privacy & Compliance: GDPR, CCPA, HIPAA Complete Guide",
    description: "Comprehensive legal and technical guide for smart lock data privacy compliance. Includes GDPR Article-by-Article implementation, CCPA requirements, HIPAA BAA templates, biometric data regulations (BIPA), data subject rights automation, privacy impact assessments, and real penalty case studies.",
    category: 'security',
    pubDate: '2024-02-17',
    wordCount: 5200,
    readingTime: 21,
    keywords: ["smart lock GDPR compliance", "access control data privacy", "CCPA smart lock requirements", "HIPAA access control logs", "biometric data privacy BIPA", "data subject rights automation"],
    tags: ["data-privacy", "gdpr", "ccpa", "hipaa", "compliance", "bipa"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["threat-modeling-security-architecture", "credential-management-best-practices", "maintenance-troubleshooting-guide"],
    relatedTools: ["privacy-impact-assessment", "data-retention-calculator", "dsar-automation-tool"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-security-complete-analysis': {
    slug: 'smart-lock-security-complete-analysis',
    title: "Smart Lock Security: Complete 2026 Analysis & Best Practices",
    description: "Comprehensive security analysis of smart locks. Threat modeling, attack vectors, protocol security comparison, encryption standards, and practical defense strategies with real-world vulnerability case studies.",
    category: 'security',
    pubDate: '2024-11-22',
    wordCount: 4500,
    readingTime: 18,
    keywords: ["smart lock security", "smart lock vulnerabilities", "smart lock encryption", "zwave s2 security", "smart lock threat model"],
    tags: ["security", "encryption", "threat-model", "vulnerabilities"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'audit-trail-forensic-analysis': {
    slug: 'audit-trail-forensic-analysis',
    title: "Smart Lock Audit Trail & Forensic Analysis: Complete Investigation Guide",
    description: "Comprehensive technical guide for smart lock audit logging, forensic investigation, and anomaly detection. Includes HIPAA/SOX compliance requirements, tamper-proof log design, real-time monitoring, ML-based anomaly detection, forensic analysis methodologies, and real investigation case studies.",
    category: 'security',
    pubDate: '2024-02-18',
    wordCount: 5500,
    readingTime: 22,
    keywords: ["smart lock audit trail", "access control forensics", "audit log compliance HIPAA", "anomaly detection access control", "forensic investigation smart locks", "tamper-proof logging"],
    tags: ["audit-trail", "forensics", "compliance", "anomaly-detection", "investigation", "siem"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["threat-modeling-security-architecture", "data-privacy-compliance-guide", "credential-management-best-practices"],
    relatedTools: ["log-analyzer", "anomaly-detector", "forensic-timeline-builder"],
    updatedAt: '2026-02-15',
  },
  'multiple-failed-code-attempts': {
    slug: 'multiple-failed-code-attempts',
    title: "Multiple Failed Code Attempts - Lockout and Security Response",
    description: "Handle multiple failed PIN attempts on smart lock. Understand lockout periods, security alerts, prevent brute force attacks, and respond to suspicious activity.",
    category: 'security',
    pubDate: '2024-04-10',
    wordCount: 650,
    readingTime: 3,
    keywords: ["failed attempts", "lockout", "wrong PIN", "security alert", "brute force"],
    tags: ["security", "lockout", "alerts"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["secure-smart-lock-best-practices", "smart-lock-code-not-working"],
    updatedAt: '2026-02-15',
  },
  'secure-smart-lock-best-practices': {
    slug: 'secure-smart-lock-best-practices',
    title: "Smart Lock Security Best Practices - Complete Hardening Guide",
    description: "Secure your smart lock with proven best practices. Strong codes, access management, network security, firmware updates, and monitoring to prevent unauthorized access.",
    category: 'security',
    pubDate: '2024-03-18',
    wordCount: 900,
    readingTime: 4,
    keywords: ["smart lock security", "secure smart lock", "smart lock best practices", "prevent hacking", "smart lock safety"],
    tags: ["security", "best-practices", "hardening"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-security-analysis", "zwave-s2-security-architecture"],
    updatedAt: '2026-02-15',
  },

  // ==================== INSTALLATION ====================
  'smart-lock-battery-life-guide': {
    slug: 'smart-lock-battery-life-guide',
    title: "Smart Lock Battery Life: Complete 2026 Optimization Guide",
    description: "Comprehensive guide to maximizing smart lock battery life. Protocol comparison, RF optimization, battery chemistry, diagnostic tools, and proven strategies to extend battery life from 3 months to 18 months.",
    category: 'installation',
    pubDate: '2024-11-22',
    wordCount: 5000,
    readingTime: 20,
    keywords: ["smart lock battery life", "maximize battery life", "smart lock battery drain", "wifi lock battery", "zigbee lock battery"],
    tags: ["battery", "optimization", "maintenance"],
    isPillar: true,
    isSupport: false,
    featured: true,
    updatedAt: '2026-02-15',
  },
  'calibrate-smart-lock': {
    slug: 'calibrate-smart-lock',
    title: "How to Calibrate Smart Lock - Fix Position Drift Issues",
    description: "Calibrate smart lock to fix incomplete lock/unlock, wrong status, or motor position drift. Step-by-step calibration for all lock brands to restore accurate operation.",
    category: 'installation',
    pubDate: '2024-04-04',
    wordCount: 700,
    readingTime: 4,
    keywords: ["calibrate smart lock", "lock calibration", "position drift", "reset lock position", "motor calibration"],
    tags: ["calibration", "maintenance", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-shows-wrong-status", "smart-lock-wont-lock-unlock-completely"],
    updatedAt: '2026-02-15',
  },
  'clean-maintain-smart-lock': {
    slug: 'clean-maintain-smart-lock',
    title: "How to Clean and Maintain Smart Lock - Monthly Care Guide",
    description: "Complete smart lock cleaning and maintenance guide. Clean keypad, lubricate mechanism, check alignment, prevent corrosion, and extend lock lifespan with monthly care routine.",
    category: 'installation',
    pubDate: '2024-03-15',
    wordCount: 900,
    readingTime: 4,
    keywords: ["clean smart lock", "smart lock maintenance", "lubricate smart lock", "smart lock care", "maintain keypad"],
    tags: ["maintenance", "cleaning", "care"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-battery-life-guide", "maximize-smart-lock-battery-life"],
    updatedAt: '2026-02-15',
  },
  'door-sensor-not-working': {
    slug: 'door-sensor-not-working',
    title: "Smart Lock Door Sensor Not Working - Fix DoorSense Issues",
    description: "Fix door sensor that will not detect open/closed status. Troubleshoot DoorSense, door position sensor, magnetic sensor, and restore accurate door status reporting.",
    category: 'installation',
    pubDate: '2024-03-29',
    wordCount: 750,
    readingTime: 4,
    keywords: ["door sensor not working", "doorsense failed", "door position sensor", "sensor malfunction", "door status wrong"],
    tags: ["sensor", "doorsense", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-shows-wrong-status", "install-smart-lock-step-by-step"],
    updatedAt: '2026-02-15',
  },
  'emergency-battery-died-locked-out': {
    slug: 'emergency-battery-died-locked-out',
    title: "Emergency: Smart Lock Battery Died, Locked Out - Quick Recovery",
    description: "Emergency guide to unlock smart lock when battery dies and you're locked out. 9V battery jump-start, backup key access, and locksmith alternatives for all smart lock brands.",
    category: 'installation',
    pubDate: '2024-02-27',
    wordCount: 950,
    readingTime: 4,
    keywords: ["smart lock battery dead locked out", "9V battery smart lock", "emergency unlock smart lock", "locked out no battery", "smart lock emergency power"],
    tags: ["emergency", "battery", "locked-out"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-battery-emergency", "smart-lock-battery-life-guide"],
    updatedAt: '2026-02-15',
  },
  'how-to-change-smart-lock-battery': {
    slug: 'how-to-change-smart-lock-battery',
    title: "How to Change Smart Lock Battery - Step by Step Guide",
    description: "Complete guide to changing smart lock batteries. When to replace, which batteries to use, proper installation procedure, and post-replacement testing for all lock brands.",
    category: 'installation',
    pubDate: '2024-02-28',
    wordCount: 900,
    readingTime: 4,
    keywords: ["change smart lock battery", "replace smart lock battery", "smart lock battery replacement", "which batteries for smart lock", "how often replace battery"],
    tags: ["battery", "maintenance", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-lock-battery-life-guide", "smart-lock-battery-dies-too-fast"],
    updatedAt: '2026-02-15',
  },
  'install-smart-lock-step-by-step': {
    slug: 'install-smart-lock-step-by-step',
    title: "How to Install Smart Lock: Complete Step-by-Step Guide",
    description: "Complete smart lock installation guide for DIY installation. Measure door, remove old lock, install smart lock correctly, test thoroughly. Works for Yale, Schlage, Kwikset, August locks.",
    category: 'installation',
    pubDate: '2024-03-05',
    wordCount: 1000,
    readingTime: 5,
    keywords: ["install smart lock", "smart lock installation", "DIY smart lock install", "smart lock setup", "how to install smart lock"],
    tags: ["installation", "how-to", "DIY"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["door-compatibility-guide", "smart-lock-wont-pair"],
    relatedTools: ["door-lock-compatibility-checker"],
    updatedAt: '2026-02-15',
  },
  'smart-lock-setup-checklist': {
    slug: 'smart-lock-setup-checklist',
    title: "Smart Lock Initial Setup Checklist - Complete Configuration Guide",
    description: "Complete smart lock setup checklist. Step-by-step initial configuration, test all features, optimize settings, and ensure reliable operation before daily use.",
    category: 'installation',
    pubDate: '2024-04-17',
    wordCount: 650,
    readingTime: 3,
    keywords: ["setup checklist", "initial setup", "configuration guide", "first time setup", "lock setup"],
    tags: ["setup", "checklist", "configuration"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["install-smart-lock-step-by-step", "test-smart-lock-after-install", "pair-smart-lock-with-hub"],
    updatedAt: '2026-02-15',
  },
  'test-smart-lock-after-install': {
    slug: 'test-smart-lock-after-install',
    title: "How to Test Smart Lock After Installation - Complete Checklist",
    description: "Comprehensive smart lock testing checklist after installation. Verify alignment, test all access methods, stress test reliability, and ensure proper setup before daily use.",
    category: 'installation',
    pubDate: '2024-03-12',
    wordCount: 900,
    readingTime: 4,
    keywords: ["test smart lock", "smart lock testing", "verify installation", "smart lock checklist", "post-installation testing"],
    tags: ["testing", "installation", "verification"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["install-smart-lock-step-by-step", "smart-lock-jammed-wont-turn"],
    updatedAt: '2026-02-15',
  },
  'update-smart-lock-firmware': {
    slug: 'update-smart-lock-firmware',
    title: "How to Update Smart Lock Firmware Safely",
    description: "Update smart lock firmware to fix bugs, add features, and improve security. Step-by-step update process, troubleshooting failed updates, and best practices for all lock brands.",
    category: 'installation',
    pubDate: '2024-03-10',
    wordCount: 900,
    readingTime: 4,
    keywords: ["update smart lock firmware", "firmware update failed", "smart lock software update", "update lock firmware", "firmware upgrade"],
    tags: ["firmware", "maintenance", "updates"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["complete-troubleshooting-guide", "improve-connection-stability"],
    updatedAt: '2026-02-15',
  },

  // ==================== INTEGRATION ====================
  'enterprise-system-integration': {
    slug: 'enterprise-system-integration',
    title: "Smart Lock Enterprise System Integration: Complete Technical Guide",
    description: "Deep dive into integrating smart locks with HR systems, calendar platforms, visitor management, and building automation. Includes API architectures, code examples, error handling strategies, and real-world implementation patterns.",
    category: 'integration',
    pubDate: '2024-02-05',
    wordCount: 4800,
    readingTime: 19,
    keywords: ["smart lock API integration", "HR system integration smart lock", "calendar integration access control", "enterprise access automation", "building automation integration", "smart lock webhook integration"],
    tags: ["api-integration", "automation", "enterprise", "hr-systems", "calendar-sync"],
    isPillar: false,
    isSupport: false,
    featured: true,
    relatedArticles: ["office-access-control", "multi-unit-buildings", "smart-lock-protocols-overview"],
    relatedTools: ["integration-roi-calculator", "api-compatibility-checker"],
    updatedAt: '2026-02-15',
  },
  'doorbell-smart-lock-integration': {
    slug: 'doorbell-smart-lock-integration',
    title: "Smart Lock and Video Doorbell Integration - Complete Setup",
    description: "Integrate smart lock with video doorbell. See who's at door before unlocking remotely, automate based on doorbell press, and create seamless entry experience.",
    category: 'integration',
    pubDate: '2024-04-09',
    wordCount: 700,
    readingTime: 4,
    keywords: ["doorbell lock integration", "video doorbell smart lock", "unlock from doorbell", "doorbell automation", "see before unlock"],
    tags: ["integration", "doorbell", "automation", "security"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-home-platform-integration", "set-up-lock-automations"],
    updatedAt: '2026-02-15',
  },
  'local-vs-cloud-architecture': {
    slug: 'local-vs-cloud-architecture',
    title: "Local vs Cloud Smart Lock Architecture: Complete Comparison",
    description: "Technical analysis of local hub versus cloud-based smart lock architectures. Compare latency, reliability, privacy, offline capability, and costs to choose the right architecture for your deployment.",
    category: 'integration',
    pubDate: '2024-01-29',
    wordCount: 3600,
    readingTime: 14,
    keywords: ["local smart lock control", "cloud smart lock", "smart lock privacy", "offline smart lock", "smart lock architecture", "local hub vs cloud"],
    tags: ["architecture", "privacy", "local-control", "cloud", "reliability"],
    isPillar: true,
    isSupport: false,
    featured: true,
    relatedArticles: ["smart-lock-protocols-overview", "smart-lock-security-complete-analysis", "zigbee-vs-zwave-comparison"],
    relatedTools: ["offline-resilience-scorecard", "protocol-selection-wizard"],
    updatedAt: '2026-02-15',
  },
  'set-up-lock-automations': {
    slug: 'set-up-lock-automations',
    title: "How to Set Up Smart Lock Automations - Complete Guide",
    description: "Create smart lock automations for auto-lock, geo-fence unlock, schedule-based access, and integrate with smart home routines. Platform-specific guides for HomeKit, Alexa, Google Home.",
    category: 'integration',
    pubDate: '2024-03-23',
    wordCount: 900,
    readingTime: 4,
    keywords: ["smart lock automation", "auto lock setup", "geofence unlock", "schedule lock", "smart home routines"],
    tags: ["automation", "routines", "smart-home", "how-to"],
    isPillar: false,
    isSupport: true,
    featured: false,
    relatedArticles: ["smart-home-platform-integration", "auto-unlock-not-working"],
    updatedAt: '2026-02-15',
  },
  // ==================== RESOURCES ====================
  'cloud-vs-local-cost': {
    slug: 'cloud-vs-local-cost',
    title: "Cloud vs. Local Smart Locks: The 10-Year TCO & 'Hidden' Exit Costs",
    description: "Most buyers analyze 3-year costs. We analyze 10. Discover why the 'Hardware Refresh Cycle' and 'Per-User' fees make Cloud systems 300% more expensive than you think.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 1100,
    readingTime: 6,
    keywords: ["cloud vs local smart lock", "smart lock tco", "access control cost analysis", "self-hosted smart lock", "saas fees", "hardware refresh cycle", "per user pricing"],
    tags: ["data-table", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'smart-lock-saas-value': {
    slug: 'smart-lock-saas-value',
    title: "SaaS Value Metrics: Is the 'Smart Lock Tax' Worth It? (2026 Analysis)",
    description: "Why pay $6/month for a lock you own? We break down the 'Access as a Service' model, calculating the exact ROI of PMS integrations, liability protection, and operational efficiency.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 1100,
    readingTime: 6,
    keywords: ["smart lock subscription roi", "access as a service", "saas value metrics", "pms integration benefits", "smart lock operational efficiency", "rekeying cost savings"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'rssi-dbm-explained': {
    slug: 'rssi-dbm-explained',
    title: "Understanding Signal Strength (RSSI): Why 'Full Bars' Is A Lie",
    description: "Why does -70dBm mean 'Good' for Wi-Fi but 'Critical' for Zigbee? We decode the logarithmic math of RSSI vs LQI and why Signal-to-Noise Ratio matters more than raw power.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 1000,
    readingTime: 5,
    keywords: ["rssi explained", "smart lock signal strength", "dbm values meaning", "zigbee lqi vs rssi", "signal to noise ratio", "wifi signal strength for locks", "lqi scale"],
    tags: ["glossary", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'rf-interference-materials': {
    slug: 'rf-interference-materials',
    title: "RF Interference Materials: The 'Silent Killers' of Smart Home Signals",
    description: "Why does your lock fail when the bathroom door closes? A physics-based guide to material attenuation (dB Loss) for 2.4GHz vs 900MHz signals. Stucco, Mirrors, and Metal explained.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 900,
    readingTime: 5,
    keywords: ["rf attenuation table", "signal loss by material", "stucco interference", "faraday cage homes", "900mhz vs 2.4ghz penetration", "smart lock range"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'locksmith-labor-rates': {
    slug: 'locksmith-labor-rates',
    title: "Locksmith Labor Rates 2026: Commercial vs Residential Cost Breakdown",
    description: "Don't get sticker shock. We analyze 2026 national averages for Trip Charges, Fresh Installs, and Commercial Retrofits. See why a 'Simple Swap' can range from $125 to $500.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 1000,
    readingTime: 5,
    keywords: ["locksmith rates 2026", "commercial locksmith cost", "residential smart lock install", "fresh install vs retrofit", "access control installation cost", "trip charge"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'hidden-installation-costs': {
    slug: 'hidden-installation-costs',
    title: "Hidden Installation Costs: The 'Budget Killers' of Smart Lock Projects",
    description: "Identifies the top 5 unexpected costs that blow up smart lock budgets. From door alignment issues to Wi-Fi bridge redundancy, learn what salesmen won't tell you.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 950,
    readingTime: 5,
    keywords: ["hidden costs", "smart lock installation", "door alignment", "wifi bridge cost", "budget planning", "retrofit costs"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'protocol-power-draw-table': {
    slug: 'protocol-power-draw-table',
    title: "IoT Protocol Power Draw: Why Your Smart Lock Batteries Die So Fast",
    description: "Why does Wi-Fi kill batteries in 3 months while Zigbee lasts 18? We break down the physics of TX/RX currents, Connection Overhead, and the 'Sleep Ratio'.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 950,
    readingTime: 5,
    keywords: ["iot power consumption", "smart lock battery life", "zigbee vs wifi power", "zwave active current", "esp32 power draw", "nrf52 current consumption"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'what-is-quiescent-current': {
    slug: 'what-is-quiescent-current',
    title: "Understanding Quiescent Current: The Vampire That Kills Batteries",
    description: "Why 'doing nothing' is the hardest job for a smart lock. We explain Standby Leakage, Vampire Draw (µA), and why your batteries drain even if you never open the door.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 850,
    readingTime: 4,
    keywords: ["quiescent current", "smart lock battery drain", "standby power", "vampire draw", "electronics leakage", "battery life calculation", "microamps"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'ansi-bhma-grading-table': {
    slug: 'ansi-bhma-grading-table',
    title: "ANSI/BHMA Grading Standards: Decoding Smart Lock Durability",
    description: "What is the difference between Grade 1, 2, and 3? We break down the cycle tests, sledgehammer impact ratings, and the A156.25 electronics standard.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 900,
    readingTime: 5,
    keywords: ["ansi bhma grades", "smart lock durability", "grade 1 vs grade 2 lock", "security rating", "cycle test", "deadbolt strength", "ansi a156.25"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'fire-rating-guide': {
    slug: 'fire-rating-guide',
    title: "Fire Ratings & Smart Locks: The UL 10C Guide",
    description: "Can you put a smart lock on a fire door? We explain UL 10C Positive Pressure testing, the risks of retrofitting, and why 'Fire Rated' does not mean 'Fire Proof'.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 850,
    readingTime: 4,
    keywords: ["ul 10c fire rating", "smart lock fire door retrofit", "positive pressure test", "fire rated vs fire proof", "20 minute fire door", "commercial smart lock code"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'anti-pick-bump-glossary': {
    slug: 'anti-pick-bump-glossary',
    title: "Anti-Pick & Anti-Bump: The Physical Security Glossary",
    description: "Burglars don't play fair. We explain Lock Bumping, Drilling, and Picking, and the specific smart lock features (sidebars, spool pins) that defeat them.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 750,
    readingTime: 4,
    keywords: ["anti pick", "anti bump", "lock security", "drill resistance", "high security locks", "lock bumping protection"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'smart-home-protocol-specs-table': {
    slug: 'smart-home-protocol-specs-table',
    title: "Smart Home Protocol Specs: The Ultimate Technical Cheat Sheet (2026)",
    description: "Direct technical comparison of Z-Wave 800, Zigbee 3.0, Thread, and Wi-Fi 6. We compare frequency, bandwidth, max nodes, security encryption, and mesh capabilities.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 1100,
    readingTime: 6,
    keywords: ["smart home protocols", "zwave 800 vs zigbee 3.0", "thread matter protocol details", "iot mesh network comparison", "aes-128 encryption", "smart lock security standards"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'mesh-topology-guide': {
    slug: 'mesh-topology-guide',
    title: "Mesh Topology Explained",
    description: "How your smart lock talks to your hub through other devices.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 500,
    readingTime: 3,
    keywords: ["mesh network", "zigbee router", "end device", "z-wave repeater", "smart lock connectivity"],
    tags: ["glossary", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'fire-rating-ul-codes': {
    slug: 'fire-rating-ul-codes',
    title: "Fire Ratings & UL Codes: When Smart Locks Can (and Can't) Be Used",
    description: "Fire inspectors are failing smart lock installs correctly. Learn about UL 10C, 20-minute ratings, and why you cannot modify a fire door for a smart lock.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 900,
    readingTime: 5,
    keywords: ["fire rating", "ul codes", "smart lock fire door", "ul 10c", "commercial fire code", "nfpa 80"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'ada-compliance-checklist': {
    slug: 'ada-compliance-checklist',
    title: "ADA Compliance Checklist: Smart Locks for Accessibility",
    description: "US Federal Law requires locks to be accessible. We explain the 'No Pinch/No Twist' rule, handle shapes, and mounting heights required for ADA compliance.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 800,
    readingTime: 4,
    keywords: ["ada compliance", "accessible locks", "lever vs knob", "smart lock disability access", "mounting height"],
    tags: ["checklist", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'standard-door-dimensions-table': {
    slug: 'standard-door-dimensions-table',
    title: "Standard Door Dimensions: The Pre-Purchase Measurement Guide",
    description: "Will it fit? The definitive guide to Backset, Bore Size, Door Thickness, and Stile Width. Don't drill a hole until you read this Table of Standards.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 750,
    readingTime: 4,
    keywords: ["door dimensions", "backset measurement", "bore hole", "door thickness", "smart lock fit", "stile width"],
    tags: ["data-table", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'lock-anatomy-glossary': {
    slug: 'lock-anatomy-glossary',
    title: "Lock Anatomy: Deep Dive",
    description: "Understanding the key components of a deadbolt assembly.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 450,
    readingTime: 3,
    keywords: ["lock anatomy", "deadbolt parts", "strike plate", "latch bolt", "smart lock hardware"],
    tags: ["glossary"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'ada-compliance-guide': {
    slug: 'ada-compliance-guide',
    title: "ADA Compliance & Smart Locks: The Complete Guide (Rule 404.2.3)",
    description: "Is your keypad legal? We explain the 'Startlingly Simple' test for ADA compliance in smart locks, mounting heights, and why round knobs are illegal in rentals.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 850,
    readingTime: 4,
    keywords: ["ada compliance smart lock", "rule 404.2.3", "door hardware requirements", "lever vs knob legal", "smart lock mounting height", "rental property lock laws"],
    tags: ["glossary", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'wire-gauge-calculator-steps': {
    slug: 'wire-gauge-calculator-steps',
    title: "Wire Gauge & Voltage Drop: The 12V/24V Smart Lock Guide",
    description: "Why does your magnetic lock fail? It's probably Voltage Drop. We explain how to calculate AWG wire thickness for 12V and 24V cable runs.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 850,
    readingTime: 4,
    keywords: ["wire gauge calculator", "12v voltage drop", "smart lock wiring", "24v cable run", "awg chart", "electric strike power issues"],
    tags: ["data-table", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'door-alignment-guide': {
    slug: 'door-alignment-guide',
    title: "Door Alignment Guide: Fixing the 'Jamming Deadbolt'",
    description: "Why does your smart lock say 'Jamming'? It's usually not the lock; it's the door. Learn the Lipstick Test and the 3-Inch Screw trick.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 800,
    readingTime: 4,
    keywords: ["door alignment troubleshooting", "smart lock jamming fix", "deadbolt friction", "strike plate adjustment", "3 inch screw hinge fix", "lipstick test door"],
    tags: ["how-to", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'encryption-standards-guide': {
    slug: 'encryption-standards-guide',
    title: "Smart Lock Encryption: AES-128, ChaCha20 & The Future of Security",
    description: "Is your smart lock hackable? We explain the difference between AES-128 (Zigbee) and ChaCha20 (Matter), and why 'Bank Grade Security' is a meaningless marketing term.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 850,
    readingTime: 4,
    keywords: ["smart lock encryption", "aes-128 vs chacha20", "matter protocol security", "zigbee encryption keys", "iot hacking defense", "tls 1.3 smart home"],
    tags: ["glossary", "standard"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'privacy-policy-template': {
    slug: 'privacy-policy-template',
    title: "Smart Home Privacy Guide: The 'Data Minimalism' Checklist",
    description: "Is your smart lock spying on you? We explain 'Data Minimization', Local vs Cloud storage, and how to read a Privacy Policy like a lawyer.",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 800,
    readingTime: 4,
    keywords: ["smart home privacy policy", "data minimization iot", "local vs cloud storage privacy", "gdpr for smart home", "ccpa smart lock rights", "iot data collection checklist"],
    tags: ["checklist", "decision-guide"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
  'troubleshooting-z-wave-range': {
    slug: 'troubleshooting-z-wave-range',
    title: "Z-Wave Range Troubleshooting: Fixing Offline Locks",
    description: "Is your smart lock showing 'Offline'? We explain Z-Wave Mesh, the 4-Hop Limit, and why you need a Repeater (and where to put it).",
    category: 'resources',
    pubDate: '2024-05-20',
    wordCount: 800,
    readingTime: 4,
    keywords: ["z-wave range extender", "smart lock offline fix", "z-wave mesh network healing", "repeaters for smart locks", "interference troubleshooting", "908 mhz frequency"],
    tags: ["how-to", "troubleshooting"],
    isPillar: false,
    isSupport: true,
    featured: false,
    updatedAt: '2026-02-15',
  },
};

/**
 * 按类别获取文章列表
 */
export function getArticlesByCategory(category: string): ArticleMetadata[] {
  return Object.values(articleRegistry).filter(
    (article) => article.category === category
  );
}

/**
 * 获取特色文章
 */
export function getFeaturedArticles(): ArticleMetadata[] {
  return Object.values(articleRegistry).filter((article) => article.featured);
}

/**
 * 获取核心支柱文章
 */
export function getPillarArticles(): ArticleMetadata[] {
  return Object.values(articleRegistry).filter((article) => article.isPillar);
}

/**
 * 根据slug获取文章
 */
export function getArticleBySlug(slug: string): ArticleMetadata | undefined {
  return articleRegistry[slug];
}

/**
 * 获取所有文章
 */
export function getAllArticles(): ArticleMetadata[] {
  return Object.values(articleRegistry);
}
