import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { config as loadEnv } from 'dotenv'
import { BrandModel } from '../lib/db/brand-models'
import { getCanonicalComparisonHref } from '../lib/seo/priority-comparisons'

const root = join(fileURLToPath(new URL('..', import.meta.url)))
const redirectsPath = join(root, 'public/_redirects')

loadEnv({ path: join(root, '.env.local'), quiet: true })
loadEnv({ path: join(root, '.env'), quiet: true })

function uniqueLines(lines: string[]) {
  return [...new Set(lines)]
}

async function main() {
  const brands = await BrandModel.getAll()
  const lines = [
    '# Generated by scripts/generate-static-redirects.ts. Do not edit by hand.',
    '/articles/use-cases/long-term-rental-property-strategy /articles/use-cases/long-term-rental-strategy 301',
  ]

  for (const sourceBrand of brands) {
    for (const targetBrand of brands) {
      if (sourceBrand.slug === targetBrand.slug) continue

      const sourcePath = `/compare/${sourceBrand.slug}-vs-${targetBrand.slug}`
      const canonicalPath = getCanonicalComparisonHref(sourceBrand.slug, targetBrand.slug)
      if (sourcePath !== canonicalPath) {
        lines.push(`${sourcePath} ${canonicalPath} 301`)
      }
    }
  }

  lines.push('/use-cases/* /articles/use-cases/:splat 301')

  mkdirSync(dirname(redirectsPath), { recursive: true })
  writeFileSync(redirectsPath, `${uniqueLines(lines).join('\n')}\n`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
